// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin._Assertions")
open class _Assertions: JavaObject {

}
extension JavaClass<_Assertions> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: _Assertions!

  @JavaStaticField(isFinal: true)
  public var ENABLED: Bool

  @JavaStaticMethod
  public func getENABLED$annotations()
}
