// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text._OneToManyTitlecaseMappingsKt")
open class _OneToManyTitlecaseMappingsKt: JavaObject {

}
extension JavaClass<_OneToManyTitlecaseMappingsKt> {
  @JavaStaticMethod
  public func titlecaseImpl(_ arg0: UInt16) -> String
}
