// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaKitCollection
import JavaRuntime
import JavaUtil

@JavaClass("kotlin.collections.AbstractMutableMap", implements: Map<JavaObject, JavaObject>.self)
open class AbstractMutableMap<K: AnyJavaObject, V: AnyJavaObject>: JavaObject {
  @JavaMethod
  open func getValues() -> JavaCollection<JavaObject>!

  @JavaMethod
  open func size() -> Int32

  @JavaMethod
  open func put(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  open func values() -> JavaCollection<JavaObject>!

  @JavaMethod
  open func entrySet() -> JavaSet<Map.Entry<JavaObject, JavaObject>>!

  @JavaMethod
  open func keySet() -> JavaSet<JavaObject>!

  @JavaMethod
  open func getSize() -> Int32

  @JavaMethod
  open func getEntries() -> JavaSet!

  @JavaMethod
  open func getKeys() -> JavaSet<JavaObject>!
}
extension AbstractMutableMap {
  @JavaClass("java.util.AbstractMap$SimpleEntry", implements: Map.Entry<JavaObject, JavaObject>.self, Serializable.self)
  open class SimpleEntry<K: AnyJavaObject, V: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaObject?, _ arg1: JavaObject?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Map.Entry<JavaObject, JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getValue() -> JavaObject!

  @JavaMethod
  open func getKey() -> JavaObject!

  @JavaMethod
  open func setValue(_ arg0: JavaObject?) -> JavaObject!
  }
}
extension AbstractMutableMap {
  @JavaClass("java.util.AbstractMap$SimpleImmutableEntry", implements: Map.Entry<JavaObject, JavaObject>.self, Serializable.self)
  open class SimpleImmutableEntry<K: AnyJavaObject, V: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaObject?, _ arg1: JavaObject?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Map.Entry<JavaObject, JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getValue() -> JavaObject!

  @JavaMethod
  open func getKey() -> JavaObject!

  @JavaMethod
  open func setValue(_ arg0: JavaObject?) -> JavaObject!
  }
}
