// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.AbstractDoubleTimeSource", implements: TimeSource.WithComparableMarks.self)
open class AbstractDoubleTimeSource: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DurationUnit?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getUnit() -> DurationUnit!

  @JavaMethod
  open func markNow() -> TimeMark!

  @JavaMethod
  open func markNow() -> ComparableTimeMark!

  @JavaMethod
  open func read() -> Double
}
extension JavaClass<AbstractDoubleTimeSource> {
  @JavaStaticField(isFinal: true)
  public var Companion: TimeSource.Companion!
}
