// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension AbstractList {
  @JavaClass("kotlin.collections.AbstractList$SubList", implements: RandomAccess.self)
  open class SubList<E: AnyJavaObject>: AbstractList {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: AbstractList<JavaObject>?, _ arg1: Int32, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func get(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  open override func getSize() -> Int32
  }
}
extension JavaClass {
  @JavaStaticField(isFinal: true)
  public var Companion: AbstractList.Companion!
}
