// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime
import JavaUtil

extension AbstractMap {
  @JavaClass("kotlin.collections.AbstractMap$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  open func entryHashCode$kotlin_stdlib(_ arg0: Map.Entry<JavaObject, JavaObject>?) -> Int32

  @JavaMethod
  open func entryToString$kotlin_stdlib(_ arg0: Map.Entry<JavaObject, JavaObject>?) -> String

  @JavaMethod
  open func entryEquals$kotlin_stdlib(_ arg0: Map.Entry<JavaObject, JavaObject>?, _ arg1: JavaObject?) -> Bool
  }
}
