// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.AbstractMutableSet", implements: JavaSet<JavaObject>.self, KMutableSet.self)
open class AbstractMutableSet<E: AnyJavaObject>: JavaObject {
  @JavaMethod
  open func size() -> Int32

  @JavaMethod
  open func add(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func getSize() -> Int32
}
