// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension AbstractList {
  @JavaClass("kotlin.collections.AbstractList$ListIteratorImpl", implements: ListIterator<JavaObject>.self)
  open class ListIteratorImpl: AbstractList.IteratorImpl {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: AbstractList?, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func add(_ arg0: JavaObject?)

  @JavaMethod
  open func set(_ arg0: JavaObject?)

  @JavaMethod
  open func nextIndex() -> Int32

  @JavaMethod
  open func previousIndex() -> Int32

  @JavaMethod
  open func hasPrevious() -> Bool

  @JavaMethod
  open func previous() -> JavaObject!
  }
}
