// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension AbstractList {
  @JavaClass("kotlin.collections.AbstractList$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func checkBoundsIndexes$kotlin_stdlib(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32)

  @JavaMethod
  open func newCapacity$kotlin_stdlib(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaMethod
  open func orderedHashCode$kotlin_stdlib(_ arg0: JavaCollection<JavaObject>?) -> Int32

  @JavaMethod
  open func orderedEquals$kotlin_stdlib(_ arg0: JavaCollection<JavaObject>?, _ arg1: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func checkElementIndex$kotlin_stdlib(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func checkPositionIndex$kotlin_stdlib(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func checkRangeIndexes$kotlin_stdlib(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32)
  }
}
