// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension AbstractSet {
  @JavaClass("kotlin.collections.AbstractSet$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  open func unorderedHashCode$kotlin_stdlib(_ arg0: JavaCollection<JavaObject>?) -> Int32

  @JavaMethod
  open func setEquals$kotlin_stdlib(_ arg0: JavaSet<JavaObject>?, _ arg1: JavaSet<JavaObject>?) -> Bool
  }
}
