// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.AbstractCoroutineContextKey", implements: CoroutineContext.Key<CoroutineContext.Element>.self)
open class AbstractCoroutineContextKey<B: AnyJavaObject, E: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CoroutineContext.Key<CoroutineContext.Element>?, _ arg1: Function1<JavaObject, CoroutineContext.Element>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func tryCast$kotlin_stdlib(_ arg0: CoroutineContext.Element?) -> CoroutineContext.Element!

  @JavaMethod
  open func isSubKey$kotlin_stdlib(_ arg0: CoroutineContext.Key<JavaObject>?) -> Bool
}
