// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.collections.builders.AbstractMapBuilderEntrySet")
open class AbstractMapBuilderEntrySet<E: AnyJavaObject, K: AnyJavaObject, V: AnyJavaObject>: AbstractMutableSet {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func contains(_ arg0: JavaObject?) -> Bool
}
