// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.AbstractLongTimeSource", implements: TimeSource.WithComparableMarks.self)
open class AbstractLongTimeSource: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DurationUnit?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func read() -> Int64

  @JavaMethod
  open func getUnit() -> DurationUnit!

  @JavaMethod
  open func markNow() -> ComparableTimeMark!

  @JavaMethod
  open func markNow() -> TimeMark!
}
extension JavaClass<AbstractLongTimeSource> {
  @JavaStaticField(isFinal: true)
  public var Companion: TimeSource.Companion!

  @JavaStaticMethod
  public func access$adjustedRead(_ arg0: AbstractLongTimeSource?) -> Int64
}
