// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.AccessDeniedException")
open class AccessDeniedException: FileSystemException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, _ arg1: File?, _ arg2: String, environment: JNIEnvironment? = nil)
}
