// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.AdjustedTimeMark", implements: TimeMark.self)
open class AdjustedTimeMark: JavaObject {
  @JavaMethod
  open func getMark() -> TimeMark!

  // @JavaMethod
//  open func`plus-LRDsOJo`(_ arg0: Int64) -> TimeMark!

// @JavaMethod
//  open func`minus-LRDsOJo`(_ arg0: Int64) -> TimeMark!

@JavaMethod
  open func hasPassedNow() -> Bool

  // @JavaMethod
//  open func`elapsedNow-UwyO8pc`() -> Int64

@JavaMethod
  open func hasNotPassedNow() -> Bool

  @JavaMethod
  open func `getAdjustment-UwyO8pc`() -> Int64
}
