// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.ArrayIteratorsKt")
open class ArrayIteratorsKt: JavaObject {

}
extension JavaClass<ArrayIteratorsKt> {
  @JavaStaticMethod
  public func iterator(_ arg0: [Int64]) -> LongIterator!

  @JavaStaticMethod
  public func iterator(_ arg0: [Float]) -> FloatIterator!

  @JavaStaticMethod
  public func iterator(_ arg0: [Double]) -> DoubleIterator!

  @JavaStaticMethod
  public func iterator(_ arg0: [Bool]) -> BooleanIterator!

  @JavaStaticMethod
  public func iterator(_ arg0: [Int8]) -> ByteIterator!

  @JavaStaticMethod
  public func iterator(_ arg0: [UInt16]) -> CharIterator!

  @JavaStaticMethod
  public func iterator(_ arg0: [Int16]) -> ShortIterator!

  @JavaStaticMethod
  public func iterator(_ arg0: [Int32]) -> IntIterator!
}
