// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.ArrayDeque")
open class ArrayDeque<E: AnyJavaObject>: AbstractMutableList {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaCollection<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func get(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  open func indexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open func clear()

  @JavaMethod
  open func lastIndexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open override func add(_ arg0: Int32, _ arg1: JavaObject?)

  @JavaMethod
  open func add(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func toArray() -> [JavaObject?]

  @JavaMethod
  open func toArray(_ arg0: [JavaObject?]) -> [JavaObject?]

  @JavaMethod
  open func contains(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func last() -> JavaObject!

  @JavaMethod
  open func addAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func addAll(_ arg0: Int32, _ arg1: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func first() -> JavaObject!

  @JavaMethod
  open override func set(_ arg0: Int32, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  open override func getSize() -> Int32

  @JavaMethod
  open func addFirst(_ arg0: JavaObject?)

  @JavaMethod
  open func addLast(_ arg0: JavaObject?)

  @JavaMethod
  open func removeFirst() -> JavaObject!

  @JavaMethod
  open func removeLast() -> JavaObject!

  @JavaMethod
  open func removeRange(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func removeAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func retainAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func testToArray$kotlin_stdlib(_ arg0: [JavaObject?]) -> [JavaObject?]

  @JavaMethod
  open func testToArray$kotlin_stdlib() -> [JavaObject?]

  @JavaMethod
  open func testRemoveRange$kotlin_stdlib(_ arg0: Int32, _ arg1: Int32)

  @JavaMethod
  open func internalStructure$kotlin_stdlib(_ arg0: Function2<JavaObject, JavaObject, Unit>?)

  @JavaMethod
  open func firstOrNull() -> JavaObject!

  @JavaMethod
  open func lastOrNull() -> JavaObject!

  @JavaMethod
  open func removeFirstOrNull() -> JavaObject!

  @JavaMethod
  open func removeLastOrNull() -> JavaObject!

  @JavaMethod
  open override func removeAt(_ arg0: Int32) -> JavaObject!
}
extension JavaClass {
  @JavaStaticField(isFinal: true)
  public var Companion: ArrayDeque.Companion!
}
