// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.ArrayCharIterator")
open class ArrayCharIterator: CharIterator {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [UInt16], environment: JNIEnvironment? = nil)

  @JavaMethod
  open func hasNext() -> Bool

  @JavaMethod
  open override func nextChar() -> UInt16
}
