// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.ArrayIntIterator")
open class ArrayIntIterator: IntIterator {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [Int32], environment: JNIEnvironment? = nil)

  @JavaMethod
  open func hasNext() -> Bool

  @JavaMethod
  open override func nextInt() -> Int32
}
