// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.ArrayIntrinsicsKt")
open class ArrayIntrinsicsKt: JavaObject {

}
extension JavaClass<ArrayIntrinsicsKt> {
  @JavaStaticMethod
  public func emptyArray() -> [JavaObject?]
}
