// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.jdk7.AutoCloseableKt")
open class AutoCloseableKt: JavaObject {

}
extension JavaClass<AutoCloseableKt> {
  @JavaStaticMethod
  public func AutoCloseable$annotations()

  @JavaStaticMethod
  public func closeFinally(_ arg0: AutoCloseable?, _ arg1: Throwable?)
}
