// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.BooleanIterator", implements: JavaIterator<JavaBoolean>.self, KMappedMarker.self)
open class BooleanIterator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove()

  @JavaMethod
  open func next() -> JavaBoolean!

  @JavaMethod
  open func nextBoolean() -> Bool
}
