// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.BooleanCompanionObject")
open class BooleanCompanionObject: JavaObject {

}
extension JavaClass<BooleanCompanionObject> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: BooleanCompanionObject!
}
