// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.jvm.internal.Boxing")
open class Boxing: JavaObject {

}
extension JavaClass<Boxing> {
  @JavaStaticMethod
  public func boxInt(_ arg0: Int32) -> JavaInteger!

  @JavaStaticMethod
  public func boxChar(_ arg0: UInt16) -> JavaCharacter!

  @JavaStaticMethod
  public func boxByte(_ arg0: Int8) -> JavaByte!

  @JavaStaticMethod
  public func boxShort(_ arg0: Int16) -> JavaShort!

  @JavaStaticMethod
  public func boxBoolean(_ arg0: Bool) -> JavaBoolean!

  @JavaStaticMethod
  public func boxLong(_ arg0: Int64) -> JavaLong!

  @JavaStaticMethod
  public func boxFloat(_ arg0: Float) -> JavaFloat!

  @JavaStaticMethod
  public func boxDouble(_ arg0: Double) -> JavaDouble!
}
