// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.ByteStreamsKt")
open class ByteStreamsKt: JavaObject {

}
extension JavaClass<ByteStreamsKt> {
  @JavaStaticMethod
  public func copyTo$default(_ arg0: InputStream?, _ arg1: OutputStream?, _ arg2: Int32, _ arg3: Int32, _ arg4: JavaObject?) -> Int64

  @JavaStaticMethod
  public func readBytes$default(_ arg0: InputStream?, _ arg1: Int32, _ arg2: Int32, _ arg3: JavaObject?) -> [Int8]

  @JavaStaticMethod
  public func iterator(_ arg0: BufferedInputStream?) -> ByteIterator!

  @JavaStaticMethod
  public func readBytes(_ arg0: InputStream?, _ arg1: Int32) -> [Int8]

  @JavaStaticMethod
  public func readBytes(_ arg0: InputStream?) -> [Int8]

  @JavaStaticMethod
  public func copyTo(_ arg0: InputStream?, _ arg1: OutputStream?, _ arg2: Int32) -> Int64
}
