// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.ByteSpreadBuilder")
open class ByteSpreadBuilder: PrimitiveSpreadBuilder {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func add(_ arg0: Int8)

  @JavaMethod
  open func toArray() -> [Int8]

  @JavaMethod
  open func getSize(_ arg0: [Int8]) -> Int32

  @JavaMethod
  open override func getSize(_ arg0: JavaObject?) -> Int32
}
