// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.ByteCompanionObject")
open class ByteCompanionObject: JavaObject {

}
extension JavaClass<ByteCompanionObject> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: ByteCompanionObject!

  @JavaStaticField(isFinal: true)
  public var MIN_VALUE: Int8

  @JavaStaticField(isFinal: true)
  public var MAX_VALUE: Int8

  @JavaStaticField(isFinal: true)
  public var SIZE_BYTES: Int32

  @JavaStaticField(isFinal: true)
  public var SIZE_BITS: Int32

  @JavaStaticMethod
  public func getSIZE_BYTES$annotations()

  @JavaStaticMethod
  public func getSIZE_BITS$annotations()
}
