// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

extension CallableReference {
  @JavaClass("kotlin.jvm.internal.CallableReference$NoReceiver", implements: Serializable.self)
  open class NoReceiver: JavaObject {

  }
}
