// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.cancellation.CancellationExceptionKt")
open class CancellationExceptionKt: JavaObject {

}
extension JavaClass<CancellationExceptionKt> {
  @JavaStaticMethod
  public func CancellationException$annotations()
}
