// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension CharRange {
  @JavaClass("kotlin.ranges.CharRange$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  open func getEMPTY() -> CharRange!
  }
}
