// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.CharsKt__CharJVMKt")
open class CharsKt__CharJVMKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<CharsKt__CharJVMKt> {
  @JavaStaticMethod
  public func getCategory(_ arg0: UInt16) -> CharCategory!

  @JavaStaticMethod
  public func checkRadix(_ arg0: Int32) -> Int32

  @JavaStaticMethod
  public func digitOf(_ arg0: UInt16, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func isWhitespace(_ arg0: UInt16) -> Bool

  @JavaStaticMethod
  public func getDirectionality(_ arg0: UInt16) -> CharDirectionality!
}
