// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.ranges.CharProgressionIterator")
open class CharProgressionIterator: CharIterator {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: UInt16, _ arg1: UInt16, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getStep() -> Int32

  @JavaMethod
  open func hasNext() -> Bool

  @JavaMethod
  open override func nextChar() -> UInt16
}
