// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.ranges.CharRange", implements: ClosedRange<JavaCharacter>.self, OpenEndRange<JavaCharacter>.self)
open class CharRange: CharProgression {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: UInt16, _ arg1: UInt16, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open override func isEmpty() -> Bool

  @JavaMethod
  open func contains(_ arg0: Comparable?) -> Bool

  @JavaMethod
  open func contains(_ arg0: UInt16) -> Bool

  @JavaMethod
  open func getEndExclusive() -> JavaCharacter!

  @JavaMethod
  open func getEndExclusive() -> Comparable!

  @JavaMethod
  open func getStart() -> JavaCharacter!

  @JavaMethod
  open func getStart() -> Comparable!

  @JavaMethod
  open func getEndInclusive() -> JavaCharacter!

  @JavaMethod
  open func getEndInclusive() -> Comparable!
}
extension JavaClass<CharRange> {
  @JavaStaticField(isFinal: true)
  public var Companion: CharRange.Companion!

  @JavaStaticField(isFinal: true)
  public var Companion: CharProgression.Companion!

  @JavaStaticMethod
  public func getEndExclusive$annotations()

  @JavaStaticMethod
  public func access$getEMPTY$cp() -> CharRange!
}
