// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.CharSpreadBuilder")
open class CharSpreadBuilder: PrimitiveSpreadBuilder {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func add(_ arg0: UInt16)

  @JavaMethod
  open func toArray() -> [UInt16]

  @JavaMethod
  open func getSize(_ arg0: [UInt16]) -> Int32

  @JavaMethod
  open override func getSize(_ arg0: JavaObject?) -> Int32
}
