// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension CharProgression {
  @JavaClass("kotlin.ranges.CharProgression$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func fromClosedRange(_ arg0: UInt16, _ arg1: UInt16, _ arg2: Int32) -> CharProgression!
  }
}
