// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.CharCompanionObject")
open class CharCompanionObject: JavaObject {

}
extension JavaClass<CharCompanionObject> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: CharCompanionObject!

  @JavaStaticField(isFinal: true)
  public var MIN_VALUE: UInt16

  @JavaStaticField(isFinal: true)
  public var MAX_VALUE: UInt16

  @JavaStaticField(isFinal: true)
  public var MIN_HIGH_SURROGATE: UInt16

  @JavaStaticField(isFinal: true)
  public var MAX_HIGH_SURROGATE: UInt16

  @JavaStaticField(isFinal: true)
  public var MIN_LOW_SURROGATE: UInt16

  @JavaStaticField(isFinal: true)
  public var MAX_LOW_SURROGATE: UInt16

  @JavaStaticField(isFinal: true)
  public var MIN_SURROGATE: UInt16

  @JavaStaticField(isFinal: true)
  public var MAX_SURROGATE: UInt16

  @JavaStaticField(isFinal: true)
  public var SIZE_BYTES: Int32

  @JavaStaticField(isFinal: true)
  public var SIZE_BITS: Int32

  @JavaStaticMethod
  public func getSIZE_BYTES$annotations()

  @JavaStaticMethod
  public func getSIZE_BITS$annotations()

  @JavaStaticMethod
  public func getMIN_VALUE$annotations()

  @JavaStaticMethod
  public func getMAX_VALUE$annotations()
}
