// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.text.Charsets")
open class Charsets: JavaObject {
  @JavaMethod
  open func UTF32_LE() -> Charset!

  @JavaMethod
  open func UTF32_BE() -> Charset!

  @JavaMethod
  open func UTF32() -> Charset!
}
extension JavaClass<Charsets> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: Charsets!

  @JavaStaticField(isFinal: true)
  public var UTF_8: Charset!

  @JavaStaticField(isFinal: true)
  public var UTF_16: Charset!

  @JavaStaticField(isFinal: true)
  public var UTF_16BE: Charset!

  @JavaStaticField(isFinal: true)
  public var UTF_16LE: Charset!

  @JavaStaticField(isFinal: true)
  public var US_ASCII: Charset!

  @JavaStaticField(isFinal: true)
  public var ISO_8859_1: Charset!
}
