// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaLang
import JavaRuntime

@JavaClass("kotlin.ranges.CharProgression", implements: Iterable<JavaCharacter>.self)
open class CharProgression: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: UInt16, _ arg1: UInt16, _ arg2: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getStep() -> Int32

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func iterator() -> JavaIterator!

  @JavaMethod
  open func iterator() -> CharIterator!

  @JavaMethod
  open func getFirst() -> UInt16

  @JavaMethod
  open func getLast() -> UInt16
}
extension JavaClass<CharProgression> {
  @JavaStaticField(isFinal: true)
  public var Companion: CharProgression.Companion!
}
