// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaInterface("kotlin.ranges.ClosedFloatingPointRange", extends: ClosedRange<Comparable<JavaObject>>.self)
public struct ClosedFloatingPointRange<T: AnyJavaObject> {
  @JavaMethod
  public func lessThanOrEquals(_ arg0: Comparable<JavaObject>?, _ arg1: Comparable<JavaObject>?) -> Bool

  @JavaMethod
  public func isEmpty() -> Bool

  @JavaMethod
  public func contains(_ arg0: Comparable<JavaObject>?) -> Bool

  @JavaMethod
  public func getStart() -> Comparable<JavaObject>!

  @JavaMethod
  public func getEndInclusive() -> Comparable<JavaObject>!
}
