// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.ranges.ClosedFloatRange", implements: ClosedFloatingPointRange<JavaFloat>.self)
open class ClosedFloatRange: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Float, _ arg1: Float, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getStart() -> Comparable!

  @JavaMethod
  open func getStart() -> JavaFloat!

  @JavaMethod
  open func getEndInclusive() -> Comparable!

  @JavaMethod
  open func getEndInclusive() -> JavaFloat!

  @JavaMethod
  open func lessThanOrEquals(_ arg0: Comparable?, _ arg1: Comparable?) -> Bool

  @JavaMethod
  open func lessThanOrEquals(_ arg0: Float, _ arg1: Float) -> Bool

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func contains(_ arg0: Float) -> Bool

  @JavaMethod
  open func contains(_ arg0: Comparable?) -> Bool
}
