// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

extension ClosedRange {
  @JavaClass("kotlin.ranges.ClosedRange$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<ClosedRange.DefaultImpls> {
  @JavaStaticMethod
  public func isEmpty(_ arg0: ClosedRange<Comparable>?) -> Bool

  @JavaStaticMethod
  public func contains(_ arg0: ClosedRange<Comparable>?, _ arg1: Comparable?) -> Bool
}
