// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.ranges.ClosedRange")
public struct ClosedRange<T: AnyJavaObject> {
  @JavaMethod
  public func isEmpty() -> Bool
}
