// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

extension ClosedFloatingPointRange {
  @JavaClass("kotlin.ranges.ClosedFloatingPointRange$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<ClosedFloatingPointRange.DefaultImpls> {
  @JavaStaticMethod
  public func isEmpty(_ arg0: ClosedFloatingPointRange<Comparable>?) -> Bool

  @JavaStaticMethod
  public func contains(_ arg0: ClosedFloatingPointRange<Comparable>?, _ arg1: Comparable?) -> Bool
}
