// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.CloseableKt")
open class CloseableKt: JavaObject {

}
extension JavaClass<CloseableKt> {
  @JavaStaticMethod
  public func closeFinally(_ arg0: Closeable?, _ arg1: Throwable?)
}
