// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.CollectionsKt__ReversedViewsKt")
open class CollectionsKt__ReversedViewsKt: CollectionsKt__MutableCollectionsKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<CollectionsKt__ReversedViewsKt> {
  @JavaStaticMethod
  public func access$reverseElementIndex(_ arg0: List?, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func access$reversePositionIndex(_ arg0: List?, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func access$reverseIteratorIndex(_ arg0: List?, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func asReversed(_ arg0: List<JavaObject>?) -> List<JavaObject>!

  @JavaStaticMethod
  public func asReversedMutable(_ arg0: List<JavaObject>?) -> List<JavaObject>!
}
