// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.CollectionsKt__IteratorsJVMKt")
open class CollectionsKt__IteratorsJVMKt: CollectionsKt__IterablesKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<CollectionsKt__IteratorsJVMKt> {
  @JavaStaticMethod
  public func iterator(_ arg0: Enumeration<JavaObject>?) -> JavaIterator<JavaObject>!
}
