// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaLang
import JavaRuntime
import JavaUtil

@JavaClass("kotlin.collections.CollectionsKt__CollectionsJVMKt")
open class CollectionsKt__CollectionsJVMKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<CollectionsKt__CollectionsJVMKt> {
  @JavaStaticMethod
  public func listOf(_ arg0: JavaObject?) -> List<JavaObject>!

  @JavaStaticMethod
  public func createListBuilder() -> List<JavaObject>!

  @JavaStaticMethod
  public func createListBuilder(_ arg0: Int32) -> List<JavaObject>!

  @JavaStaticMethod
  public func shuffled(_ arg0: Iterable<JavaObject>?, _ arg1: Random?) -> List<JavaObject>!

  @JavaStaticMethod
  public func shuffled(_ arg0: Iterable<JavaObject>?) -> List<JavaObject>!

  @JavaStaticMethod
  public func terminateCollectionToArray(_ arg0: Int32, _ arg1: [JavaObject?]) -> [JavaObject?]

  @JavaStaticMethod
  public func copyToArrayOfAny(_ arg0: [JavaObject?], _ arg1: Bool) -> [JavaObject?]

  @JavaStaticMethod
  public func build(_ arg0: List<JavaObject>?) -> List<JavaObject>!
}
