// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.CollectionsKt__IteratorsKt")
open class CollectionsKt__IteratorsKt: CollectionsKt__IteratorsJVMKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<CollectionsKt__IteratorsKt> {
  @JavaStaticMethod
  public func forEach(_ arg0: JavaIterator<JavaObject>?, _ arg1: Function1<JavaObject, Unit>?)

  @JavaStaticMethod
  public func withIndex(_ arg0: JavaIterator<JavaObject>?) -> JavaIterator<IndexedValue<JavaObject>>!
}
