// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.collections.TypeAliasesKt")
open class CollectionsTypeAliasesKt: JavaObject {

}
extension JavaClass<CollectionsTypeAliasesKt> {
  @JavaStaticMethod
  public func RandomAccess$annotations()

  @JavaStaticMethod
  public func ArrayList$annotations()

  @JavaStaticMethod
  public func LinkedHashMap$annotations()

  @JavaStaticMethod
  public func HashMap$annotations()

  @JavaStaticMethod
  public func LinkedHashSet$annotations()

  @JavaStaticMethod
  public func HashSet$annotations()
}
