// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaLang
import JavaRuntime

@JavaClass("kotlin.collections.CollectionsKt__IterablesKt")
open class CollectionsKt__IterablesKt: CollectionsKt__CollectionsKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<CollectionsKt__IterablesKt> {
  @JavaStaticMethod
  public func collectionSizeOrNull(_ arg0: Iterable<JavaObject>?) -> JavaInteger!

  @JavaStaticMethod
  public func collectionSizeOrDefault(_ arg0: Iterable<JavaObject>?, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func unzip(_ arg0: Iterable<Pair<JavaObject, JavaObject>>?) -> Pair<List<JavaObject>, List<JavaObject>>!

  @JavaStaticMethod
  public func flatten(_ arg0: Iterable<Iterable<JavaObject>>?) -> List<JavaObject>!
}
