// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.CombinedContext", implements: CoroutineContext.self, Serializable.self)
open class CombinedContext: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: CoroutineContext?, _ arg1: CoroutineContext.Element?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func fold(_ arg0: JavaObject?, _ arg1: Function2<JavaObject, JavaObject, JavaObject>?) -> JavaObject!

  @JavaMethod
  open func minusKey(_ arg0: CoroutineContext.Key<JavaObject>?) -> CoroutineContext!

  @JavaMethod
  open func get(_ arg0: CoroutineContext.Key<CoroutineContext.Element>?) -> CoroutineContext.Element!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func plus(_ arg0: CoroutineContext?) -> CoroutineContext!
}
