// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

extension CombinedContext {
  @JavaClass("kotlin.coroutines.CombinedContext$Serialized", implements: Serializable.self)
  open class Serialized: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [CoroutineContext?], environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getElements() -> [CoroutineContext?]
  }
}
extension JavaClass<CombinedContext.Serialized> {
  @JavaStaticField(isFinal: true)
  public var Companion: CombinedContext.Serialized.Companion!
}
