// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension CombinedContext.Serialized {
  @JavaClass("kotlin.coroutines.CombinedContext$Serialized$Companion")
  open class Companion: JavaObject {

  }
}
