// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.jvm.internal.CompletedContinuation", implements: Continuation<JavaObject>.self)
open class CompletedContinuation: JavaObject {
  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func getContext() -> CoroutineContext!

  @JavaMethod
  open func resumeWith(_ arg0: JavaObject?)
}
extension JavaClass<CompletedContinuation> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: CompletedContinuation!
}
