// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaInterface("kotlin.time.ComparableTimeMark", extends: TimeMark.self, Comparable<ComparableTimeMark>.self)
public struct ComparableTimeMark {
  @JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func hashCode() -> Int32

  @JavaMethod
  public func compareTo(_ arg0: ComparableTimeMark?) -> Int32

@JavaMethod
  public func hasPassedNow() -> Bool

  @JavaMethod
  public func hasNotPassedNow() -> Bool

  @JavaMethod
  public func compareTo(_ arg0: JavaObject?) -> Int32
}
