// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.comparisons.ComparisonsKt___ComparisonsJvmKt")
open class ComparisonsKt___ComparisonsJvmKt: ComparisonsKt__ComparisonsKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<ComparisonsKt___ComparisonsJvmKt> {
  @JavaStaticMethod
  public func maxOf(_ arg0: Int8, _ arg1: [Int8]) -> Int8

  @JavaStaticMethod
  public func maxOf(_ arg0: Comparable<JavaObject>?, _ arg1: [Comparable<JavaObject>?]) -> Comparable<JavaObject>!

  @JavaStaticMethod
  public func maxOf(_ arg0: Double, _ arg1: [Double]) -> Double

  @JavaStaticMethod
  public func maxOf(_ arg0: Float, _ arg1: [Float]) -> Float

  @JavaStaticMethod
  public func maxOf(_ arg0: Int64, _ arg1: [Int64]) -> Int64

  @JavaStaticMethod
  public func maxOf(_ arg0: Int32, _ arg1: [Int32]) -> Int32

  @JavaStaticMethod
  public func maxOf(_ arg0: Int16, _ arg1: [Int16]) -> Int16

  @JavaStaticMethod
  public func maxOf(_ arg0: Comparable<JavaObject>?, _ arg1: Comparable<JavaObject>?) -> Comparable<JavaObject>!

  @JavaStaticMethod
  public func maxOf(_ arg0: Comparable<JavaObject>?, _ arg1: Comparable<JavaObject>?, _ arg2: Comparable<JavaObject>?) -> Comparable<JavaObject>!

  @JavaStaticMethod
  public func minOf(_ arg0: Comparable<JavaObject>?, _ arg1: [Comparable<JavaObject>?]) -> Comparable<JavaObject>!

  @JavaStaticMethod
  public func minOf(_ arg0: Int8, _ arg1: [Int8]) -> Int8

  @JavaStaticMethod
  public func minOf(_ arg0: Double, _ arg1: [Double]) -> Double

  @JavaStaticMethod
  public func minOf(_ arg0: Float, _ arg1: [Float]) -> Float

  @JavaStaticMethod
  public func minOf(_ arg0: Int64, _ arg1: [Int64]) -> Int64

  @JavaStaticMethod
  public func minOf(_ arg0: Int32, _ arg1: [Int32]) -> Int32

  @JavaStaticMethod
  public func minOf(_ arg0: Int16, _ arg1: [Int16]) -> Int16

  @JavaStaticMethod
  public func minOf(_ arg0: Comparable<JavaObject>?, _ arg1: Comparable<JavaObject>?) -> Comparable<JavaObject>!

  @JavaStaticMethod
  public func minOf(_ arg0: Comparable<JavaObject>?, _ arg1: Comparable<JavaObject>?, _ arg2: Comparable<JavaObject>?) -> Comparable<JavaObject>!
}
