// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.comparisons.ComparisonsKt___ComparisonsKt")
open class ComparisonsKt___ComparisonsKt: ComparisonsKt___ComparisonsJvmKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
