// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.ranges.ComparableRange", implements: ClosedRange<Comparable<JavaObject>>.self)
open class ComparableRange<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Comparable<JavaObject>?, _ arg1: Comparable<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getStart() -> Comparable<JavaObject>!

  @JavaMethod
  open func getEndInclusive() -> Comparable<JavaObject>!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func contains(_ arg0: Comparable<JavaObject>?) -> Bool
}
