// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.comparisons.ComparisonsKt__ComparisonsKt")
open class ComparisonsKt__ComparisonsKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<ComparisonsKt__ComparisonsKt> {
  @JavaStaticMethod
  public func compareValues(_ arg0: Comparable<JavaObject>?, _ arg1: Comparable<JavaObject>?) -> Int32

  @JavaStaticMethod
  public func compareValuesBy(_ arg0: JavaObject?, _ arg1: JavaObject?, _ arg2: [Function1<JavaObject, Comparable<JavaObject>>?]) -> Int32
}
