// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ComparableTimeMark {
  @JavaClass("kotlin.time.ComparableTimeMark$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<ComparableTimeMark.DefaultImpls> {
  @JavaStaticMethod
  public func`minus-LRDsOJo`(_ arg0: ComparableTimeMark?, _ arg1: Int64) -> ComparableTimeMark!

@JavaStaticMethod
  public func hasPassedNow(_ arg0: ComparableTimeMark?) -> Bool

  @JavaStaticMethod
  public func hasNotPassedNow(_ arg0: ComparableTimeMark?) -> Bool

  @JavaStaticMethod
  public func compareTo(_ arg0: ComparableTimeMark?, _ arg1: ComparableTimeMark?) -> Int32
}
