// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.contracts.ConditionalEffect", extends: Effect.self)
public struct ConditionalEffect {

}
