// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.ConstantsKt")
open class ConstantsKt: JavaObject {

}
extension JavaClass<ConstantsKt> {
  @JavaStaticField(isFinal: true)
  public var DEFAULT_BUFFER_SIZE: Int32

  @JavaStaticField(isFinal: true)
  public var DEFAULT_BLOCK_SIZE: Int32

  @JavaStaticField(isFinal: true)
  public var MINIMUM_BLOCK_SIZE: Int32
}
