// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.ConsoleKt")
open class ConsoleKt: JavaObject {

}
extension JavaClass<ConsoleKt> {
  @JavaStaticMethod
  public func readLine() -> String

  @JavaStaticMethod
  public func readln() -> String

  @JavaStaticMethod
  public func readlnOrNull() -> String
}
