// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.coroutines.Continuation")
public struct Continuation<T: AnyJavaObject> {
  @JavaMethod
  public func resumeWith(_ arg0: JavaObject?)

  @JavaMethod
  public func getContext() -> CoroutineContext!
}
