// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.jvm.internal.ContinuationImpl")
open class ContinuationImpl: BaseContinuationImpl {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Continuation<JavaObject>?, _ arg1: CoroutineContext?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Continuation<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func intercepted() -> Continuation<JavaObject>!

  @JavaMethod
  open override func releaseIntercepted()

  @JavaMethod
  open func getContext() -> CoroutineContext!
}
