// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.coroutines.ContinuationInterceptor", extends: CoroutineContext.Element.self)
public struct ContinuationInterceptor {
  @JavaMethod
  public func minusKey(_ arg0: CoroutineContext.Key<JavaObject>?) -> CoroutineContext!

  @JavaMethod
  public func interceptContinuation(_ arg0: Continuation<JavaObject>?) -> Continuation<JavaObject>!

  @JavaMethod
  public func releaseInterceptedContinuation(_ arg0: Continuation<JavaObject>?)

  @JavaMethod
  public func get(_ arg0: CoroutineContext.Key<CoroutineContext.Element>?) -> CoroutineContext.Element!

  @JavaMethod
  public func fold(_ arg0: JavaObject?, _ arg1: Function2<JavaObject, JavaObject, JavaObject>?) -> JavaObject!

  @JavaMethod
  public func getKey() -> CoroutineContext.Key<JavaObject>!

  @JavaMethod
  public func plus(_ arg0: CoroutineContext?) -> CoroutineContext!
}
extension JavaClass<ContinuationInterceptor> {
  @JavaStaticField(isFinal: true)
  public var Key: ContinuationInterceptor.Key!
}
