// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ContractBuilder {
  @JavaClass("kotlin.contracts.ContractBuilder$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<ContractBuilder.DefaultImpls> {
  @JavaStaticMethod
  public func callsInPlace$default(_ arg0: ContractBuilder?, _ arg1: Function?, _ arg2: InvocationKind?, _ arg3: Int32, _ arg4: JavaObject?) -> CallsInPlace!
}
