// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.path.CopyActionResult")
open class CopyActionResult: JavaObject {
  public enum CopyActionResultCases: Equatable {
    case CONTINUE
    case SKIP_SUBTREE
    case TERMINATE
  }

  public var enumValue: CopyActionResultCases! {
    let classObj = self.javaClass
    if self.equals(classObj.CONTINUE?.as(JavaObject.self)) {
      return CopyActionResultCases.CONTINUE
    } else if self.equals(classObj.SKIP_SUBTREE?.as(JavaObject.self)) {
      return CopyActionResultCases.SKIP_SUBTREE
    } else if self.equals(classObj.TERMINATE?.as(JavaObject.self)) {
      return CopyActionResultCases.TERMINATE
    } else {
      return nil
    }
  }

  public convenience init(_ enumValue: CopyActionResultCases, environment: JNIEnvironment? = nil) {
    let _environment = if let environment {
      environment
    } else {
      try! JavaVirtualMachine.shared().environment()
    }
    let classObj = try! JavaClass<CopyActionResult>(environment: _environment)
    switch enumValue {
      case .CONTINUE:
        if let CONTINUE = classObj.CONTINUE {
          self.init(javaHolder: CONTINUE.javaHolder)
        } else {
          fatalError("Enum value CONTINUE was unexpectedly nil, please re-run Java2Swift on the most updated Java class")
        }
      case .SKIP_SUBTREE:
        if let SKIP_SUBTREE = classObj.SKIP_SUBTREE {
          self.init(javaHolder: SKIP_SUBTREE.javaHolder)
        } else {
          fatalError("Enum value SKIP_SUBTREE was unexpectedly nil, please re-run Java2Swift on the most updated Java class")
        }
      case .TERMINATE:
        if let TERMINATE = classObj.TERMINATE {
          self.init(javaHolder: TERMINATE.javaHolder)
        } else {
          fatalError("Enum value TERMINATE was unexpectedly nil, please re-run Java2Swift on the most updated Java class")
        }
    }
  }
}
extension JavaClass<CopyActionResult> {
  @JavaStaticField(isFinal: true)
  public var CONTINUE: CopyActionResult!

  @JavaStaticField(isFinal: true)
  public var SKIP_SUBTREE: CopyActionResult!

  @JavaStaticField(isFinal: true)
  public var TERMINATE: CopyActionResult!

  @JavaStaticMethod
  public func values() -> [CopyActionResult?]

  @JavaStaticMethod
  public func valueOf(_ arg0: String) -> CopyActionResult!

  @JavaStaticMethod
  public func getEntries() -> EnumEntries<CopyActionResult>!
}
