// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaInterface("kotlin.io.path.CopyActionContext")
public struct CopyActionContext {
  @JavaMethod
  public func copyToIgnoringExistingDirectory(_ arg0: Path?, _ arg1: Path?, _ arg2: Bool) -> CopyActionResult!
}
