// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension CoroutineContext {
  @JavaInterface("kotlin.coroutines.CoroutineContext$Key")
  public struct Key<E: AnyJavaObject> {

  }
}
