// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension CoroutineContext.Element {
  @JavaClass("kotlin.coroutines.CoroutineContext$Element$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<CoroutineContext.Element.DefaultImpls> {
  @JavaStaticMethod
  public func get(_ arg0: CoroutineContext.Element?, _ arg1: CoroutineContext.Key<CoroutineContext.Element>?) -> CoroutineContext.Element!

  @JavaStaticMethod
  public func plus(_ arg0: CoroutineContext.Element?, _ arg1: CoroutineContext?) -> CoroutineContext!

  @JavaStaticMethod
  public func minusKey(_ arg0: CoroutineContext.Element?, _ arg1: CoroutineContext.Key<JavaObject>?) -> CoroutineContext!

  @JavaStaticMethod
  public func fold(_ arg0: CoroutineContext.Element?, _ arg1: JavaObject?, _ arg2: Function2<JavaObject, JavaObject, JavaObject>?) -> JavaObject!
}
