// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.jvm.internal.DebugProbesKt")
open class DebugProbesKt: JavaObject {

}
extension JavaClass<DebugProbesKt> {
  @JavaStaticMethod
  public func probeCoroutineCreated(_ arg0: Continuation<JavaObject>?) -> Continuation<JavaObject>!

  @JavaStaticMethod
  public func probeCoroutineResumed(_ arg0: Continuation<JavaObject>?)

  @JavaStaticMethod
  public func probeCoroutineSuspended(_ arg0: Continuation<JavaObject>?)
}
