// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

@JavaInterface("kotlin.coroutines.jvm.internal.DebugMetadata", extends: Annotation.self)
public struct DebugMetadata {
  @JavaMethod
  public func i() -> [Int32]

  @JavaMethod
  public func s() -> [String]

  @JavaMethod
  public func c() -> String

  @JavaMethod
  public func n() -> [String]

  @JavaMethod
  public func f() -> String

  @JavaMethod
  public func l() -> [Int32]

  @JavaMethod
  public func m() -> String

  @JavaMethod
  public func v() -> Int32

  @JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func toString() -> String

  @JavaMethod
  public func hashCode() -> Int32

  @JavaMethod
  public func annotationType() -> JavaClass<Annotation>!
}
