// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.coroutines.jvm.internal.DebugMetadataKt")
open class DebugMetadataKt: JavaObject {

}
extension JavaClass<DebugMetadataKt> {
  @JavaStaticMethod
  public func getSpilledVariableFieldMapping(_ arg0: BaseContinuationImpl?) -> [String]

  @JavaStaticMethod
  public func getStackTraceElement(_ arg0: BaseContinuationImpl?) -> StackTraceElement!
}
