// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.encoding.DecodeInputStream")
open class DecodeInputStream: InputStream {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: InputStream?, _ arg1: Base64?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func close()

  @JavaMethod
  open override func read() -> Int32

  @JavaMethod
  open override func read(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32) -> Int32
}
