// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.DeepRecursiveFunction")
open class DeepRecursiveFunction<T: AnyJavaObject, R: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Function3<JavaObject, JavaObject, JavaObject, JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getBlock$kotlin_stdlib() -> Function3<DeepRecursiveScope<JavaObject, JavaObject>, JavaObject, Continuation<JavaObject>, JavaObject>!
}
