// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.DefaultConstructorMarker")
open class DefaultConstructorMarker: JavaObject {

}
