// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.properties.Delegates")
open class Delegates: JavaObject {
  @JavaMethod
  open func notNull() -> ReadWriteProperty<JavaObject, JavaObject>!

  @JavaMethod
  open func observable(_ arg0: JavaObject?, _ arg1: Function3<JavaObject, JavaObject, JavaObject, Unit>?) -> ReadWriteProperty<JavaObject, JavaObject>!

  @JavaMethod
  open func vetoable(_ arg0: JavaObject?, _ arg1: Function3<JavaObject, JavaObject, JavaObject, JavaBoolean>?) -> ReadWriteProperty<JavaObject, JavaObject>!
}
extension JavaClass<Delegates> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: Delegates!
}
