// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

@JavaInterface("kotlin.Deprecated", extends: Annotation.self)
public struct Deprecated {
  @JavaMethod
  public func message() -> String

  @JavaMethod
  public func replaceWith() -> ReplaceWith!

  @JavaMethod
  public func level() -> DeprecationLevel!

  @JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func toString() -> String

  @JavaMethod
  public func hashCode() -> Int32

  @JavaMethod
  public func annotationType() -> JavaClass<Annotation>!
}
