// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.path.DirectoryEntriesReader")
open class DirectoryEntriesReader: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Bool, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getFollowLinks() -> Bool

  @JavaMethod
  open func readEntries(_ arg0: PathNode?) -> List<PathNode>!
}
