// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.DoubleIterator", implements: JavaIterator<JavaDouble>.self, KMappedMarker.self)
open class DoubleIterator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove()

  @JavaMethod
  open func next() -> JavaDouble!

  @JavaMethod
  open func nextDouble() -> Double
}
