// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaInterface("kotlin.sequences.DropTakeSequence", extends: Sequence<JavaObject>.self)
public struct DropTakeSequence<T: AnyJavaObject> {
  @JavaMethod
  public func take(_ arg0: Int32) -> Sequence<JavaObject>!

  @JavaMethod
  public func drop(_ arg0: Int32) -> Sequence<JavaObject>!

  @JavaMethod
  public func iterator() -> JavaIterator<JavaObject>!
}
