// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.sequences.DropWhileSequence", implements: Sequence<JavaObject>.self)
open class DropWhileSequence<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Sequence<JavaObject>?, _ arg1: Function1<JavaObject, JavaBoolean>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func iterator() -> JavaIterator<JavaObject>!
}
extension JavaClass {
  @JavaStaticMethod
  public func access$getSequence$p<T: AnyJavaObject>(_ arg0: DropWhileSequence?) -> Sequence! where ObjectType == DropWhileSequence<T>

  @JavaStaticMethod
  public func access$getPredicate$p<T: AnyJavaObject>(_ arg0: DropWhileSequence?) -> Function1! where ObjectType == DropWhileSequence<T>
}
