// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Duration {
  @JavaClass("kotlin.time.Duration$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func convert(_ arg0: Double, _ arg1: DurationUnit?, _ arg2: DurationUnit?) -> Double

  @JavaMethod
  open func`getNEG_INFINITE-UwyO8pc$kotlin_stdlib`() -> Int64

  @JavaMethod
  open func`getINFINITE-UwyO8pc`() -> Int64

  @JavaMethod
  open func`nanoseconds-UwyO8pc`(_ arg0: Int32) -> Int64

  @JavaMethod
  open func`nanoseconds-UwyO8pc`(_ arg0: Double) -> Int64

  @JavaMethod
  open func`nanoseconds-UwyO8pc`(_ arg0: Int64) -> Int64

  @JavaMethod
  open func`microseconds-UwyO8pc`(_ arg0: Int32) -> Int64

  @JavaMethod
  open func`microseconds-UwyO8pc`(_ arg0: Int64) -> Int64

  @JavaMethod
  open func`microseconds-UwyO8pc`(_ arg0: Double) -> Int64

  @JavaMethod
  open func`milliseconds-UwyO8pc`(_ arg0: Int64) -> Int64

  @JavaMethod
  open func`milliseconds-UwyO8pc`(_ arg0: Int32) -> Int64

  @JavaMethod
  open func`milliseconds-UwyO8pc`(_ arg0: Double) -> Int64

  @JavaMethod
  open func`parseIsoString-UwyO8pc`(_ arg0: String) -> Int64

  @JavaMethod
  open func`parseOrNull-FghU774`(_ arg0: String) -> Duration!

  @JavaMethod
  open func`parseIsoStringOrNull-FghU774`(_ arg0: String) -> Duration!

  @JavaMethod
  open func`getZERO-UwyO8pc`() -> Int64

  @JavaMethod
  open func`seconds-UwyO8pc`(_ arg0: Double) -> Int64

  @JavaMethod
  open func`seconds-UwyO8pc`(_ arg0: Int32) -> Int64

  @JavaMethod
  open func`seconds-UwyO8pc`(_ arg0: Int64) -> Int64

  @JavaMethod
  open func`minutes-UwyO8pc`(_ arg0: Int64) -> Int64

  @JavaMethod
  open func`minutes-UwyO8pc`(_ arg0: Int32) -> Int64

  @JavaMethod
  open func`minutes-UwyO8pc`(_ arg0: Double) -> Int64

  @JavaMethod
  open func`hours-UwyO8pc`(_ arg0: Int32) -> Int64

  @JavaMethod
  open func`hours-UwyO8pc`(_ arg0: Double) -> Int64

  @JavaMethod
  open func`hours-UwyO8pc`(_ arg0: Int64) -> Int64

  @JavaMethod
  open func`days-UwyO8pc`(_ arg0: Int64) -> Int64

  @JavaMethod
  open func`days-UwyO8pc`(_ arg0: Double) -> Int64

  @JavaMethod
  open func`days-UwyO8pc`(_ arg0: Int32) -> Int64

  @JavaMethod
  open func `parse-UwyO8pc`(_ arg0: String) -> Int64
  }
}
extension JavaClass<Duration.Companion> {
  @JavaStaticMethod
  public func`getMilliseconds-UwyO8pc$annotations`(_ arg0: Int32)

@JavaStaticMethod
  public func`getMilliseconds-UwyO8pc$annotations`(_ arg0: Int64)

@JavaStaticMethod
  public func`getMilliseconds-UwyO8pc$annotations`(_ arg0: Double)

@JavaStaticMethod
  public func`getMicroseconds-UwyO8pc$annotations`(_ arg0: Double)

@JavaStaticMethod
  public func`getMicroseconds-UwyO8pc$annotations`(_ arg0: Int32)

@JavaStaticMethod
  public func`getMicroseconds-UwyO8pc$annotations`(_ arg0: Int64)

@JavaStaticMethod
  public func`getNanoseconds-UwyO8pc$annotations`(_ arg0: Double)

@JavaStaticMethod
  public func`getNanoseconds-UwyO8pc$annotations`(_ arg0: Int32)

@JavaStaticMethod
  public func`getNanoseconds-UwyO8pc$annotations`(_ arg0: Int64)

@JavaStaticMethod
  public func`getSeconds-UwyO8pc$annotations`(_ arg0: Double)

@JavaStaticMethod
  public func`getSeconds-UwyO8pc$annotations`(_ arg0: Int64)

@JavaStaticMethod
  public func`getSeconds-UwyO8pc$annotations`(_ arg0: Int32)

@JavaStaticMethod
  public func`getMinutes-UwyO8pc$annotations`(_ arg0: Int64)

@JavaStaticMethod
  public func`getMinutes-UwyO8pc$annotations`(_ arg0: Int32)

@JavaStaticMethod
  public func`getMinutes-UwyO8pc$annotations`(_ arg0: Double)

@JavaStaticMethod
  public func`getHours-UwyO8pc$annotations`(_ arg0: Double)

@JavaStaticMethod
  public func`getHours-UwyO8pc$annotations`(_ arg0: Int64)

@JavaStaticMethod
  public func`getHours-UwyO8pc$annotations`(_ arg0: Int32)

@JavaStaticMethod
  public func`getDays-UwyO8pc$annotations`(_ arg0: Double)

@JavaStaticMethod
  public func`getDays-UwyO8pc$annotations`(_ arg0: Int32)

@JavaStaticMethod
  public func `getDays-UwyO8pc$annotations`(_ arg0: Int64)
}
