// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension DurationUnitKt__DurationUnitJvmKt {
  @JavaClass("kotlin.time.DurationUnitKt__DurationUnitJvmKt$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}
extension JavaClass<DurationUnitKt__DurationUnitJvmKt.WhenMappings> {
  @JavaStaticField(isFinal: true)
  public var $EnumSwitchMapping$0: [Int32]
}
