// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.DurationJvmKt")
open class DurationJvmKt: JavaObject {

}
extension JavaClass<DurationJvmKt> {
  @JavaStaticMethod
  public func getDurationAssertionsEnabled() -> Bool

  @JavaStaticMethod
  public func formatToExactDecimals(_ arg0: Double, _ arg1: Int32) -> String
}
