// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.DurationUnitKt__DurationUnitJvmKt")
open class DurationUnitKt__DurationUnitJvmKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<DurationUnitKt__DurationUnitJvmKt> {
  @JavaStaticMethod
  public func convertDurationUnit(_ arg0: Double, _ arg1: DurationUnit?, _ arg2: DurationUnit?) -> Double

  @JavaStaticMethod
  public func convertDurationUnit(_ arg0: Int64, _ arg1: DurationUnit?, _ arg2: DurationUnit?) -> Int64

  @JavaStaticMethod
  public func convertDurationUnitOverflow(_ arg0: Int64, _ arg1: DurationUnit?, _ arg2: DurationUnit?) -> Int64
}
