// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.DurationUnitKt__DurationUnitKt")
open class DurationUnitKt__DurationUnitKt: DurationUnitKt__DurationUnitJvmKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<DurationUnitKt__DurationUnitKt> {
  @JavaStaticMethod
  public func shortName(_ arg0: DurationUnit?) -> String

  @JavaStaticMethod
  public func durationUnitByShortName(_ arg0: String) -> DurationUnit!

  @JavaStaticMethod
  public func durationUnitByIsoChar(_ arg0: UInt16, _ arg1: Bool) -> DurationUnit!
}
