// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.jdk8.DurationConversionsJDK8Kt")
open class DurationConversionsJDK8Kt: JavaObject {

}
