// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension DurationUnitKt__DurationUnitKt {
  @JavaClass("kotlin.time.DurationUnitKt__DurationUnitKt$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}
extension JavaClass<DurationUnitKt__DurationUnitKt.WhenMappings> {
  @JavaStaticField(isFinal: true)
  public var $EnumSwitchMapping$0: [Int32]
}
