// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension DurationUnitKt__DurationUnitKt {
  @JavaClass("kotlin.time.DurationUnitKt__DurationUnitKt$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}