// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.time.Duration", implements: Comparable<Duration>.self)
open class Duration: JavaObject {
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open func`unbox-impl`() -> Int64

@JavaMethod
  open func `compareTo-LRDsOJo`(_ arg0: Int64) -> Int32
}
extension JavaClass<Duration> {
  @JavaStaticField(isFinal: true)
  public var Companion: Duration.Companion!

  @JavaStaticMethod
  public func getNanosecondsComponent$annotations()

  @JavaStaticMethod
  public func`truncateTo-UwyO8pc$kotlin_stdlib`(_ arg0: Int64, _ arg1: DurationUnit?) -> Int64

@JavaStaticMethod
  public func`getInWholeNanoseconds-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`getAbsoluteValue-UwyO8pc`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`getInWholeDays-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`getHoursComponent-impl`(_ arg0: Int64) -> Int32

@JavaStaticMethod
  public func`getMinutesComponent-impl`(_ arg0: Int64) -> Int32

@JavaStaticMethod
  public func`getSecondsComponent-impl`(_ arg0: Int64) -> Int32

@JavaStaticMethod
  public func`getNanosecondsComponent-impl`(_ arg0: Int64) -> Int32

@JavaStaticMethod
  public func`getInWholeHours-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`getInWholeMinutes-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`getInWholeSeconds-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func getHoursComponent$annotations()

  @JavaStaticMethod
  public func getMinutesComponent$annotations()

  @JavaStaticMethod
  public func getSecondsComponent$annotations()

  @JavaStaticMethod
  public func getInDays$annotations()

  @JavaStaticMethod
  public func getInHours$annotations()

  @JavaStaticMethod
  public func getInMinutes$annotations()

  @JavaStaticMethod
  public func getInSeconds$annotations()

  @JavaStaticMethod
  public func`getInMilliseconds-impl`(_ arg0: Int64) -> Double

@JavaStaticMethod
  public func getInMilliseconds$annotations()

  @JavaStaticMethod
  public func`getInMicroseconds-impl`(_ arg0: Int64) -> Double

@JavaStaticMethod
  public func getInMicroseconds$annotations()

  @JavaStaticMethod
  public func`getInNanoseconds-impl`(_ arg0: Int64) -> Double

@JavaStaticMethod
  public func getInNanoseconds$annotations()

  @JavaStaticMethod
  public func`getInWholeMilliseconds-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`getInWholeMicroseconds-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`toLongNanoseconds-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`toLongMilliseconds-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`toString-impl$default`(_ arg0: Int64, _ arg1: DurationUnit?, _ arg2: Int32, _ arg3: Int32, _ arg4: JavaObject?) -> String

@JavaStaticMethod
  public func access$getINFINITE$cp() -> Int64

  @JavaStaticMethod
  public func access$getNEG_INFINITE$cp() -> Int64

  @JavaStaticMethod
  public func`toInt-impl`(_ arg0: Int64, _ arg1: DurationUnit?) -> Int32

@JavaStaticMethod
  public func`toLong-impl`(_ arg0: Int64, _ arg1: DurationUnit?) -> Int64

@JavaStaticMethod
  public func`toDouble-impl`(_ arg0: Int64, _ arg1: DurationUnit?) -> Double

@JavaStaticMethod
  public func`hashCode-impl`(_ arg0: Int64) -> Int32

@JavaStaticMethod
  public func`equals-impl`(_ arg0: Int64, _ arg1: JavaObject?) -> Bool

@JavaStaticMethod
  public func`equals-impl0`(_ arg0: Int64, _ arg1: Int64) -> Bool

@JavaStaticMethod
  public func`toString-impl`(_ arg0: Int64) -> String

@JavaStaticMethod
  public func`toString-impl`(_ arg0: Int64, _ arg1: DurationUnit?, _ arg2: Int32) -> String

@JavaStaticMethod
  public func`box-impl`(_ arg0: Int64) -> Duration!

@JavaStaticMethod
  public func`minus-LRDsOJo`(_ arg0: Int64, _ arg1: Int64) -> Int64

@JavaStaticMethod
  public func`plus-LRDsOJo`(_ arg0: Int64, _ arg1: Int64) -> Int64

@JavaStaticMethod
  public func`isInfinite-impl`(_ arg0: Int64) -> Bool

@JavaStaticMethod
  public func`div-UwyO8pc`(_ arg0: Int64, _ arg1: Double) -> Int64

@JavaStaticMethod
  public func`div-UwyO8pc`(_ arg0: Int64, _ arg1: Int32) -> Int64

@JavaStaticMethod
  public func`unaryMinus-UwyO8pc`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`isFinite-impl`(_ arg0: Int64) -> Bool

@JavaStaticMethod
  public func`times-UwyO8pc`(_ arg0: Int64, _ arg1: Int32) -> Int64

@JavaStaticMethod
  public func`times-UwyO8pc`(_ arg0: Int64, _ arg1: Double) -> Int64

@JavaStaticMethod
  public func`isPositive-impl`(_ arg0: Int64) -> Bool

@JavaStaticMethod
  public func`div-LRDsOJo`(_ arg0: Int64, _ arg1: Int64) -> Double

@JavaStaticMethod
  public func`toComponents-impl`(_ arg0: Int64, _ arg1: Function5<JavaObject, JavaObject, JavaObject, JavaObject, JavaObject, JavaObject>?) -> JavaObject!

@JavaStaticMethod
  public func`toComponents-impl`(_ arg0: Int64, _ arg1: Function2<JavaObject, JavaObject, JavaObject>?) -> JavaObject!

@JavaStaticMethod
  public func`toComponents-impl`(_ arg0: Int64, _ arg1: Function3<JavaObject, JavaObject, JavaObject, JavaObject>?) -> JavaObject!

@JavaStaticMethod
  public func`toComponents-impl`(_ arg0: Int64, _ arg1: Function4<JavaObject, JavaObject, JavaObject, JavaObject, JavaObject>?) -> JavaObject!

@JavaStaticMethod
  public func`getInDays-impl`(_ arg0: Int64) -> Double

@JavaStaticMethod
  public func`getInHours-impl`(_ arg0: Int64) -> Double

@JavaStaticMethod
  public func`getInMinutes-impl`(_ arg0: Int64) -> Double

@JavaStaticMethod
  public func`getInSeconds-impl`(_ arg0: Int64) -> Double

@JavaStaticMethod
  public func`toIsoString-impl`(_ arg0: Int64) -> String

@JavaStaticMethod
  public func access$getZERO$cp() -> Int64

  @JavaStaticMethod
  public func`constructor-impl`(_ arg0: Int64) -> Int64

@JavaStaticMethod
  public func`isNegative-impl`(_ arg0: Int64) -> Bool

@JavaStaticMethod
  public func `compareTo-LRDsOJo`(_ arg0: Int64, _ arg1: Int64) -> Int32
}
