// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.DurationKt")
open class DurationKt: JavaObject {

}
extension JavaClass<DurationKt> {
  @JavaStaticField(isFinal: true)
  public var NANOS_IN_MILLIS: Int32

  @JavaStaticField(isFinal: true)
  public var MAX_NANOS: Int64

  @JavaStaticField(isFinal: true)
  public var MAX_MILLIS: Int64

  @JavaStaticMethod
  public func getNanoseconds(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func getNanoseconds(_ arg0: Int32) -> Int64

  @JavaStaticMethod
  public func getNanoseconds(_ arg0: Double) -> Int64

  @JavaStaticMethod
  public func getMicroseconds(_ arg0: Int32) -> Int64

  @JavaStaticMethod
  public func getMicroseconds(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func getMicroseconds(_ arg0: Double) -> Int64

  @JavaStaticMethod
  public func getMilliseconds(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func getMilliseconds(_ arg0: Int32) -> Int64

  @JavaStaticMethod
  public func getMilliseconds(_ arg0: Double) -> Int64

  @JavaStaticMethod
  public func access$durationOf(_ arg0: Int64, _ arg1: Int32) -> Int64

  @JavaStaticMethod
  public func toDuration(_ arg0: Int64, _ arg1: DurationUnit?) -> Int64

  @JavaStaticMethod
  public func toDuration(_ arg0: Double, _ arg1: DurationUnit?) -> Int64

  @JavaStaticMethod
  public func toDuration(_ arg0: Int32, _ arg1: DurationUnit?) -> Int64

  @JavaStaticMethod
  public func access$durationOfNanosNormalized(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func access$durationOfMillisNormalized(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func access$nanosToMillis(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func access$millisToNanos(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func access$durationOfNanos(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func access$durationOfMillis(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func getNanoseconds$annotations(_ arg0: Double)

  @JavaStaticMethod
  public func getNanoseconds$annotations(_ arg0: Int32)

  @JavaStaticMethod
  public func getNanoseconds$annotations(_ arg0: Int64)

  @JavaStaticMethod
  public func getMicroseconds$annotations(_ arg0: Int32)

  @JavaStaticMethod
  public func getMicroseconds$annotations(_ arg0: Int64)

  @JavaStaticMethod
  public func getMicroseconds$annotations(_ arg0: Double)

  @JavaStaticMethod
  public func getMilliseconds$annotations(_ arg0: Int32)

  @JavaStaticMethod
  public func getMilliseconds$annotations(_ arg0: Double)

  @JavaStaticMethod
  public func getMilliseconds$annotations(_ arg0: Int64)

  @JavaStaticMethod
  public func getSeconds$annotations(_ arg0: Double)

  @JavaStaticMethod
  public func getSeconds$annotations(_ arg0: Int32)

  @JavaStaticMethod
  public func getSeconds$annotations(_ arg0: Int64)

  @JavaStaticMethod
  public func getMinutes$annotations(_ arg0: Int32)

  @JavaStaticMethod
  public func getMinutes$annotations(_ arg0: Double)

  @JavaStaticMethod
  public func getMinutes$annotations(_ arg0: Int64)

  @JavaStaticMethod
  public func getHours$annotations(_ arg0: Double)

  @JavaStaticMethod
  public func getHours$annotations(_ arg0: Int32)

  @JavaStaticMethod
  public func getHours$annotations(_ arg0: Int64)

  @JavaStaticMethod
  public func getDays$annotations(_ arg0: Int32)

  @JavaStaticMethod
  public func getDays$annotations(_ arg0: Double)

  @JavaStaticMethod
  public func getDays$annotations(_ arg0: Int64)

  @JavaStaticMethod
  public func access$parseDuration(_ arg0: String, _ arg1: Bool) -> Int64

  @JavaStaticMethod
  public func getSeconds(_ arg0: Double) -> Int64

  @JavaStaticMethod
  public func getSeconds(_ arg0: Int32) -> Int64

  @JavaStaticMethod
  public func getSeconds(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func getDays(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func getDays(_ arg0: Int32) -> Int64

  @JavaStaticMethod
  public func getDays(_ arg0: Double) -> Int64

  @JavaStaticMethod
  public func getHours(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func getHours(_ arg0: Double) -> Int64

  @JavaStaticMethod
  public func getHours(_ arg0: Int32) -> Int64

  @JavaStaticMethod
  public func getMinutes(_ arg0: Int64) -> Int64

  @JavaStaticMethod
  public func getMinutes(_ arg0: Double) -> Int64

  @JavaStaticMethod
  public func getMinutes(_ arg0: Int32) -> Int64
}
