// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.EmptyCoroutineContext", implements: CoroutineContext.self)
open class EmptyCoroutineContext: JavaObject {
  @JavaMethod
  open func fold(_ arg0: JavaObject?, _ arg1: Function2<JavaObject, JavaObject, JavaObject>?) -> JavaObject!

  @JavaMethod
  open func minusKey(_ arg0: CoroutineContext.Key<JavaObject>?) -> CoroutineContext!

  @JavaMethod
  open func get(_ arg0: CoroutineContext.Key<CoroutineContext.Element>?) -> CoroutineContext.Element!

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func plus(_ arg0: CoroutineContext?) -> CoroutineContext!
}
extension JavaClass<EmptyCoroutineContext> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: EmptyCoroutineContext!
}
