// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.EmptyList", implements: List.self, Serializable.self, RandomAccess.self)
open class EmptyList: JavaObject {
  @JavaMethod
  open func remove(_ arg0: Int32) -> JavaVoid!

  @JavaMethod
  open func remove(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func size() -> Int32

  @JavaMethod
  open func get(_ arg0: Int32) -> JavaVoid!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func indexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open func indexOf(_ arg0: JavaVoid?) -> Int32

  @JavaMethod
  open func clear()

  @JavaMethod
  open func lastIndexOf(_ arg0: JavaVoid?) -> Int32

  @JavaMethod
  open func lastIndexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func add(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func add(_ arg0: Int32, _ arg1: JavaObject?)

  @JavaMethod
  open func add(_ arg0: Int32, _ arg1: JavaVoid?)

  @JavaMethod
  open func add(_ arg0: JavaVoid?) -> Bool

  @JavaMethod
  open func subList(_ arg0: Int32, _ arg1: Int32) -> List!

  @JavaMethod
  open func toArray(_ arg0: [JavaObject?]) -> [JavaObject?]

  @JavaMethod
  open func toArray() -> [JavaObject?]

  @JavaMethod
  open func iterator() -> JavaIterator!

  @JavaMethod
  open func contains(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func contains(_ arg0: JavaVoid?) -> Bool

  @JavaMethod
  open func addAll(_ arg0: JavaCollection?) -> Bool

  @JavaMethod
  open func addAll(_ arg0: Int32, _ arg1: JavaCollection?) -> Bool

  @JavaMethod
  open func set(_ arg0: Int32, _ arg1: JavaVoid?) -> JavaVoid!

  @JavaMethod
  open func set(_ arg0: Int32, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  open func getSize() -> Int32

  @JavaMethod
  open func removeAll(_ arg0: JavaCollection?) -> Bool

  @JavaMethod
  open func retainAll(_ arg0: JavaCollection?) -> Bool

  @JavaMethod
  open func listIterator() -> ListIterator!

  @JavaMethod
  open func listIterator(_ arg0: Int32) -> ListIterator!

  @JavaMethod
  open func containsAll(_ arg0: JavaCollection?) -> Bool
}
extension JavaClass<EmptyList> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: EmptyList!
}
