// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.sequences.EmptySequence", implements: Sequence.self, DropTakeSequence.self)
open class EmptySequence: JavaObject {
  @JavaMethod
  open func iterator() -> JavaIterator!

  @JavaMethod
  open func take(_ arg0: Int32) -> Sequence!

  @JavaMethod
  open func take(_ arg0: Int32) -> EmptySequence!

  @JavaMethod
  open func drop(_ arg0: Int32) -> EmptySequence!

  @JavaMethod
  open func drop(_ arg0: Int32) -> Sequence!
}
extension JavaClass<EmptySequence> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: EmptySequence!
}
