// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.EnumCompanionObject")
open class EnumCompanionObject: JavaObject {

}
extension JavaClass<EnumCompanionObject> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: EnumCompanionObject!
}
