// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaUtilFunction
import CSwiftJavaJNI

@JavaInterface("kotlin.enums.EnumEntries")
public struct EnumEntries<E: AnyJavaObject> {
  @JavaMethod
  public func remove(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  public func remove(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func size() -> Int32

  @JavaMethod
  public func get(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func hashCode() -> Int32

  @JavaMethod
  public func indexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  public func clear()

  @JavaMethod
  public func lastIndexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  public func isEmpty() -> Bool

  @JavaMethod
  public func replaceAll(_ arg0: JavaUnaryOperator<JavaObject>?)

  @JavaMethod
  public func add(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func add(_ arg0: Int32, _ arg1: JavaObject?)

  @JavaMethod
  public func subList(_ arg0: Int32, _ arg1: Int32) -> List<JavaObject>!

  @JavaMethod
  public func toArray() -> [JavaObject?]

  @JavaMethod
  public func toArray(_ arg0: [JavaObject?]) -> [JavaObject?]

  @JavaMethod
  public func iterator() -> JavaIterator<JavaObject>!

  @JavaMethod
  public func contains(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func addAll(_ arg0: Int32, _ arg1: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  public func addAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  public func set(_ arg0: Int32, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  public func getFirst() -> JavaObject!

  @JavaMethod
  public func getLast() -> JavaObject!

  @JavaMethod
  public func addFirst(_ arg0: JavaObject?)

  @JavaMethod
  public func addLast(_ arg0: JavaObject?)

  @JavaMethod
  public func removeFirst() -> JavaObject!

  @JavaMethod
  public func removeLast() -> JavaObject!

  @JavaMethod
  public func removeAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  public func retainAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  public func listIterator() -> ListIterator<JavaObject>!

  @JavaMethod
  public func listIterator(_ arg0: Int32) -> ListIterator<JavaObject>!

  @JavaMethod
  public func reversed() -> List<JavaObject>!

  @JavaMethod
  public func containsAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  public func toArray(_ arg0: JavaIntFunction<JavaArray>?) -> [JavaObject?]

  @JavaMethod
  public func removeIf(_ arg0: JavaPredicate<JavaObject>?) -> Bool

  @JavaMethod
  public func forEach(_ arg0: JavaConsumer<JavaObject>?)
}
