// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.enums.EnumEntriesList")
open class EnumEntriesList<T: AnyJavaObject>: AbstractList {
  @JavaMethod
  open override func indexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open override func lastIndexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open override func contains(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func getSize() -> Int32
}
extension JavaClass {
  @JavaStaticField(isFinal: true)
  public var Companion: AbstractList.Companion!
}
