// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.random.FallbackThreadLocalRandom")
open class FallbackThreadLocalRandom: AbstractPlatformRandom {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<FallbackThreadLocalRandom> {
  @JavaStaticField(isFinal: true)
  public var Default: Random.Default!
}
