// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension FileTreeWalk.FileTreeWalkIterator {
  @JavaClass("kotlin.io.FileTreeWalk$FileTreeWalkIterator$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}
extension JavaClass<FileTreeWalk.FileTreeWalkIterator.WhenMappings> {
  @JavaStaticField(isFinal: true)
  public var $EnumSwitchMapping$0: [Int32]
}
