// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.FilesKt__UtilsKt")
open class FilesKt__UtilsKt: FilesKt__FileTreeWalkKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<FilesKt__UtilsKt> {
  @JavaStaticMethod
  public func deleteRecursively(_ arg0: File?) -> Bool

  @JavaStaticMethod
  public func relativeTo(_ arg0: File?, _ arg1: File?) -> File!

  @JavaStaticMethod
  public func relativeToOrSelf(_ arg0: File?, _ arg1: File?) -> File!

  @JavaStaticMethod
  public func relativeToOrNull(_ arg0: File?, _ arg1: File?) -> File!

  @JavaStaticMethod
  public func copyTo$default(_ arg0: File?, _ arg1: File?, _ arg2: Bool, _ arg3: Int32, _ arg4: Int32, _ arg5: JavaObject?) -> File!

  @JavaStaticMethod
  public func createTempDir(_ arg0: String, _ arg1: String, _ arg2: File?) -> File!

  @JavaStaticMethod
  public func toRelativeString(_ arg0: File?, _ arg1: File?) -> String

  @JavaStaticMethod
  public func copyRecursively(_ arg0: File?, _ arg1: File?, _ arg2: Bool, _ arg3: Function2<JavaObject, JavaObject, OnErrorAction>?) -> Bool

  @JavaStaticMethod
  public func createTempDir$default(_ arg0: String, _ arg1: String, _ arg2: File?, _ arg3: Int32, _ arg4: JavaObject?) -> File!

  @JavaStaticMethod
  public func copyRecursively$default(_ arg0: File?, _ arg1: File?, _ arg2: Bool, _ arg3: Function2?, _ arg4: Int32, _ arg5: JavaObject?) -> Bool

  @JavaStaticMethod
  public func getNameWithoutExtension(_ arg0: File?) -> String

  @JavaStaticMethod
  public func getInvariantSeparatorsPath(_ arg0: File?) -> String

  @JavaStaticMethod
  public func createTempFile$default(_ arg0: String, _ arg1: String, _ arg2: File?, _ arg3: Int32, _ arg4: JavaObject?) -> File!

  @JavaStaticMethod
  public func startsWith(_ arg0: File?, _ arg1: String) -> Bool

  @JavaStaticMethod
  public func startsWith(_ arg0: File?, _ arg1: File?) -> Bool

  @JavaStaticMethod
  public func endsWith(_ arg0: File?, _ arg1: String) -> Bool

  @JavaStaticMethod
  public func endsWith(_ arg0: File?, _ arg1: File?) -> Bool

  @JavaStaticMethod
  public func resolve(_ arg0: File?, _ arg1: String) -> File!

  @JavaStaticMethod
  public func resolve(_ arg0: File?, _ arg1: File?) -> File!

  @JavaStaticMethod
  public func normalize(_ arg0: File?) -> File!

  @JavaStaticMethod
  public func createTempFile(_ arg0: String, _ arg1: String, _ arg2: File?) -> File!

  @JavaStaticMethod
  public func copyTo(_ arg0: File?, _ arg1: File?, _ arg2: Bool, _ arg3: Int32) -> File!

  @JavaStaticMethod
  public func resolveSibling(_ arg0: File?, _ arg1: String) -> File!

  @JavaStaticMethod
  public func resolveSibling(_ arg0: File?, _ arg1: File?) -> File!

  @JavaStaticMethod
  public func getExtension(_ arg0: File?) -> String
}
