// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.path.FileVisitorImpl")
open class FileVisitorImpl: JavaObject {

}
