// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension FileTreeWalk {
  @JavaClass("kotlin.io.FileTreeWalk$FileTreeWalkIterator")
  open class FileTreeWalkIterator: AbstractIterator {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: FileTreeWalk?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func computeNext()
  }
}
