// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.FilesKt__FilePathComponentsKt")
open class FilesKt__FilePathComponentsKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<FilesKt__FilePathComponentsKt> {
  @JavaStaticMethod
  public func getRoot(_ arg0: File?) -> File!

  @JavaStaticMethod
  public func toComponents(_ arg0: File?) -> FilePathComponents!

  @JavaStaticMethod
  public func isRooted(_ arg0: File?) -> Bool

  @JavaStaticMethod
  public func subPath(_ arg0: File?, _ arg1: Int32, _ arg2: Int32) -> File!

  @JavaStaticMethod
  public func getRootName(_ arg0: File?) -> String
}
