// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.FileAlreadyExistsException")
open class FileAlreadyExistsException: FileSystemException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, _ arg1: File?, _ arg2: String, environment: JNIEnvironment? = nil)
}
