// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

extension FileTreeWalk {
  @JavaClass("kotlin.io.FileTreeWalk$WalkState")
  open class WalkState: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getRoot() -> File!

  @JavaMethod
  open func step() -> File!
  }
}
