// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

extension FileTreeWalk.FileTreeWalkIterator {
  @JavaClass("kotlin.io.FileTreeWalk$FileTreeWalkIterator$BottomUpDirectoryState")
  open class BottomUpDirectoryState: FileTreeWalk.DirectoryState {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: FileTreeWalk.FileTreeWalkIterator?, _ arg1: File?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func step() -> File!
  }
}
