// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension FileTreeWalk.FileTreeWalkIterator {
  @JavaClass("kotlin.io.FileTreeWalk$FileTreeWalkIterator$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}
