// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.FileSystemException")
open class FileSystemException: IOException {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, _ arg1: File?, _ arg2: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: File?, _ arg1: File?, _ arg2: String, _ arg3: Int32, _ arg4: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getFile() -> File!

  @JavaMethod
  open func getReason() -> String

  @JavaMethod
  open func getOther() -> File!
}
