// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.FloatIterator", implements: JavaIterator<JavaFloat>.self)
open class FloatIterator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove()

  @JavaMethod
  open func next() -> JavaFloat!

  @JavaMethod
  open func nextFloat() -> Float
}
