// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.jvm.functions.Function0", extends: Function<JavaObject>.self)
public struct Function0<R: AnyJavaObject> {
  @JavaMethod
  public func invoke() -> JavaObject!
}
