// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.FunctionReferenceImpl")
open class FunctionReferenceImpl: FunctionReference {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: KDeclarationContainer?, _ arg2: String, _ arg3: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: JavaClass?, _ arg2: String, _ arg3: String, _ arg4: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: JavaObject?, _ arg2: JavaClass?, _ arg3: String, _ arg4: String, _ arg5: Int32, environment: JNIEnvironment? = nil)
}
extension JavaClass<FunctionReferenceImpl> {
  @JavaStaticField(isFinal: true)
  public var NO_RECEIVER: JavaObject!
}
