// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.jvm.functions.FunctionN", extends: Function<JavaObject>.self, FunctionBase<JavaObject>.self)
public struct FunctionN<R: AnyJavaObject> {
  @JavaMethod
  public func invoke(_ arg0: [JavaObject?]) -> JavaObject!

  @JavaMethod
  public func getArity() -> Int32
}
