// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.jvm.functions.Function2", extends: Function<JavaObject>.self)
public struct Function2<P1: AnyJavaObject, P2: AnyJavaObject, R: AnyJavaObject> {
  @JavaMethod
  public func invoke(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!
}
