// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("kotlin.jvm.functions.Function21", extends: Function<JavaObject>.self)
public struct Function21<P1: AnyJavaObject, P2: AnyJavaObject, P3: AnyJavaObject, P4: AnyJavaObject, P5: AnyJavaObject, P6: AnyJavaObject, P7: AnyJavaObject, P8: AnyJavaObject, P9: AnyJavaObject, P10: AnyJavaObject, P11: AnyJavaObject, P12: AnyJavaObject, P13: AnyJavaObject, P14: AnyJavaObject, P15: AnyJavaObject, P16: AnyJavaObject, P17: AnyJavaObject, P18: AnyJavaObject, P19: AnyJavaObject, P20: AnyJavaObject, P21: AnyJavaObject, R: AnyJavaObject> {
  @JavaMethod
  public func invoke(_ arg0: JavaObject?, _ arg1: JavaObject?, _ arg2: JavaObject?, _ arg3: JavaObject?, _ arg4: JavaObject?, _ arg5: JavaObject?, _ arg6: JavaObject?, _ arg7: JavaObject?, _ arg8: JavaObject?, _ arg9: JavaObject?, _ arg10: JavaObject?, _ arg11: JavaObject?, _ arg12: JavaObject?, _ arg13: JavaObject?, _ arg14: JavaObject?, _ arg15: JavaObject?, _ arg16: JavaObject?, _ arg17: JavaObject?, _ arg18: JavaObject?, _ arg19: JavaObject?, _ arg20: JavaObject?) -> JavaObject!
}
