// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("kotlin.jvm.functions.Function3", extends: Function<JavaObject>.self)
public struct Function3<P1: AnyJavaObject, P2: AnyJavaObject, P3: AnyJavaObject, R: AnyJavaObject> {
  @JavaMethod
  public func invoke(_ arg0: JavaObject?, _ arg1: JavaObject?, _ arg2: JavaObject?) -> JavaObject!
}
