// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.jvm.functions.Function12", extends: Function<JavaObject>.self)
public struct Function12<P1: AnyJavaObject, P2: AnyJavaObject, P3: AnyJavaObject, P4: AnyJavaObject, P5: AnyJavaObject, P6: AnyJavaObject, P7: AnyJavaObject, P8: AnyJavaObject, P9: AnyJavaObject, P10: AnyJavaObject, P11: AnyJavaObject, P12: AnyJavaObject, R: AnyJavaObject> {
  @JavaMethod
  public func invoke(_ arg0: JavaObject?, _ arg1: JavaObject?, _ arg2: JavaObject?, _ arg3: JavaObject?, _ arg4: JavaObject?, _ arg5: JavaObject?, _ arg6: JavaObject?, _ arg7: JavaObject?, _ arg8: JavaObject?, _ arg9: JavaObject?, _ arg10: JavaObject?, _ arg11: JavaObject?) -> JavaObject!
}
