// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.jvm.internal.FunctionBase", extends: Function<JavaObject>.self)
public struct FunctionBase<R: AnyJavaObject> {
  @JavaMethod
  public func getArity() -> Int32
}
