// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.jvm.functions.Function1", extends: Function<JavaObject>.self)
public struct Function1<P1: AnyJavaObject, R: AnyJavaObject> {
  @JavaMethod
  public func invoke(_ arg0: JavaObject?) -> JavaObject!
}
