// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaInterface("kotlin.collections.Grouping")
public struct Grouping<T: AnyJavaObject, K: AnyJavaObject> {
  @JavaMethod
  public func sourceIterator() -> JavaIterator<JavaObject>!

  @JavaMethod
  public func keyOf(_ arg0: JavaObject?) -> JavaObject!
}
