// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension HexFormat.NumberHexFormat {
  @JavaClass("kotlin.text.HexFormat$NumberHexFormat$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getPrefix() -> String

  @JavaMethod
  open func getSuffix() -> String

  @JavaMethod
  open func getRemoveLeadingZeros() -> Bool

  @JavaMethod
  open func getMinLength() -> Int32

  @JavaMethod
  open func setPrefix(_ arg0: String)

  @JavaMethod
  open func setSuffix(_ arg0: String)

  @JavaMethod
  open func setRemoveLeadingZeros(_ arg0: Bool)

  @JavaMethod
  open func setMinLength(_ arg0: Int32)

  @JavaMethod
  open func build$kotlin_stdlib() -> HexFormat.NumberHexFormat!
  }
}
extension JavaClass<HexFormat.NumberHexFormat.Builder> {
  @JavaStaticMethod
  public func getMinLength$annotations()
}
