// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension HexFormat.BytesHexFormat {
  @JavaClass("kotlin.text.HexFormat$BytesHexFormat$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getDefault$kotlin_stdlib() -> HexFormat.BytesHexFormat!
  }
}
