// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension HexFormat.BytesHexFormat {
  @JavaClass("kotlin.text.HexFormat$BytesHexFormat$Builder")
  open class Builder: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getBytesPerLine() -> Int32

  @JavaMethod
  open func getBytesPerGroup() -> Int32

  @JavaMethod
  open func getGroupSeparator() -> String

  @JavaMethod
  open func getByteSeparator() -> String

  @JavaMethod
  open func getBytePrefix() -> String

  @JavaMethod
  open func getByteSuffix() -> String

  @JavaMethod
  open func setBytesPerLine(_ arg0: Int32)

  @JavaMethod
  open func setBytesPerGroup(_ arg0: Int32)

  @JavaMethod
  open func setGroupSeparator(_ arg0: String)

  @JavaMethod
  open func setByteSeparator(_ arg0: String)

  @JavaMethod
  open func setBytePrefix(_ arg0: String)

  @JavaMethod
  open func setByteSuffix(_ arg0: String)

  @JavaMethod
  open func build$kotlin_stdlib() -> HexFormat.BytesHexFormat!
  }
}
