// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.HexFormat")
open class HexFormat: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Bool, _ arg1: HexFormat.BytesHexFormat?, _ arg2: HexFormat.NumberHexFormat?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getUpperCase() -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func getBytes() -> HexFormat.BytesHexFormat!

  @JavaMethod
  open func getNumber() -> HexFormat.NumberHexFormat!
}
extension JavaClass<HexFormat> {
  @JavaStaticField(isFinal: true)
  public var Companion: HexFormat.Companion!

  @JavaStaticMethod
  public func access$getDefault$cp() -> HexFormat!

  @JavaStaticMethod
  public func access$getUpperCase$cp() -> HexFormat!
}
