// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension HexFormat {
  @JavaClass("kotlin.text.HexFormat$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getDefault() -> HexFormat!

  @JavaMethod
  open func getUpperCase() -> HexFormat!
  }
}
