// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.path.IllegalFileNameException")
open class IllegalFileNameException: Exception {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Path?, _ arg1: Path?, _ arg2: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Path?, environment: JNIEnvironment? = nil)
}
