// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.IndexingIterator", implements: JavaIterator<IndexedValue<JavaObject>>.self, KMappedMarker.self)
open class IndexingIterator<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaIterator<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove()

  @JavaMethod
  open func hasNext() -> Bool

  @JavaMethod
  open func next() -> IndexedValue<JavaObject>!
}
