// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.sequences.IndexingSequence", implements: Sequence<IndexedValue<JavaObject>>.self)
open class IndexingSequence<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Sequence<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func iterator() -> JavaIterator<IndexedValue<JavaObject>>!
}
extension JavaClass {
  @JavaStaticMethod
  public func access$getSequence$p<T: AnyJavaObject>(_ arg0: IndexingSequence?) -> Sequence! where ObjectType == IndexingSequence<T>
}
