// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.InitializedLazyImpl", implements: Lazy<JavaObject>.self)
open class InitializedLazyImpl<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaObject?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func isInitialized() -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func getValue() -> JavaObject!
}
