// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.IntIterator", implements: JavaIterator<JavaInteger>.self)
open class IntIterator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove()

  @JavaMethod
  open func next() -> JavaInteger!

  @JavaMethod
  open func nextInt() -> Int32
}
