// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.intrinsics.IntrinsicsKt")
open class IntrinsicsKt: IntrinsicsKt__IntrinsicsKt {

}
