// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension JDK7PlatformImplementations {
  @JavaClass("kotlin.internal.jdk7.JDK7PlatformImplementations$ReflectSdkVersion")
  open class ReflectSdkVersion: JavaObject {

  }
}
extension JavaClass<JDK7PlatformImplementations.ReflectSdkVersion> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: JDK7PlatformImplementations.ReflectSdkVersion!

  @JavaStaticField(isFinal: true)
  public var sdkVersion: JavaInteger!
}
