// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.jdk8.JvmRepeatableKt")
open class JvmRepeatableKt: JavaObject {

}
extension JavaClass<JvmRepeatableKt> {
  @JavaStaticMethod
  public func JvmRepeatable$annotations()
}
