// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitReflection
import JavaRuntime

@JavaInterface("kotlin.reflect.KAnnotatedElement")
public struct KAnnotatedElement {
  @JavaMethod
  public func getAnnotations() -> List<Annotation>!
}
