// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitReflection
import JavaRuntime
import JavaUtil

@JavaInterface("kotlin.reflect.KCallable", extends: KAnnotatedElement.self)
public struct KCallable<R: AnyJavaObject> {
  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getTypeParameters() -> List<KTypeParameter>!

  @JavaMethod
  public func isFinal() -> Bool

  @JavaMethod
  public func getReturnType() -> KType!

  @JavaMethod
  public func isOpen() -> Bool

  @JavaMethod
  public func getParameters() -> List<KParameter>!

  @JavaMethod
  public func isAbstract() -> Bool

  @JavaMethod
  public func call(_ arg0: [JavaObject?]) -> JavaObject!

  @JavaMethod
  public func callBy(_ arg0: Map<KParameter, JavaObject>?) -> JavaObject!

  @JavaMethod
  public func getVisibility() -> KVisibility!

  @JavaMethod
  public func isSuspend() -> Bool

  @JavaMethod
  public func getAnnotations() -> List<Annotation>!
}
