// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KCallable {
  @JavaClass("kotlin.reflect.KCallable$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<KCallable.DefaultImpls> {
  @JavaStaticMethod
  public func isOpen$annotations()

  @JavaStaticMethod
  public func isFinal$annotations()

  @JavaStaticMethod
  public func isSuspend$annotations()

  @JavaStaticMethod
  public func getName$annotations()

  @JavaStaticMethod
  public func isAbstract$annotations()

  @JavaStaticMethod
  public func getTypeParameters$annotations()

  @JavaStaticMethod
  public func getVisibility$annotations()
}
