// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.reflect.KClasses")
open class KClasses: JavaObject {

}
extension JavaClass<KClasses> {
  @JavaStaticMethod
  public func cast(_ arg0: KClass<JavaObject>?, _ arg1: JavaObject?) -> JavaObject!

  @JavaStaticMethod
  public func safeCast(_ arg0: KClass<JavaObject>?, _ arg1: JavaObject?) -> JavaObject!
}
