// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KClass {
  @JavaClass("kotlin.reflect.KClass$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<KClass.DefaultImpls> {
  @JavaStaticMethod
  public func isData$annotations()

  @JavaStaticMethod
  public func isFun$annotations()

  @JavaStaticMethod
  public func isOpen$annotations()

  @JavaStaticMethod
  public func isFinal$annotations()

  @JavaStaticMethod
  public func isAbstract$annotations()

  @JavaStaticMethod
  public func getTypeParameters$annotations()

  @JavaStaticMethod
  public func getVisibility$annotations()

  @JavaStaticMethod
  public func getSupertypes$annotations()

  @JavaStaticMethod
  public func getSealedSubclasses$annotations()

  @JavaStaticMethod
  public func isSealed$annotations()

  @JavaStaticMethod
  public func isInner$annotations()

  @JavaStaticMethod
  public func isCompanion$annotations()

  @JavaStaticMethod
  public func isValue$annotations()
}
