// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("kotlin.reflect.KDeclarationContainer")
public struct KDeclarationContainer {
  @JavaMethod
  public func getMembers() -> JavaCollection<KCallable<JavaObject>>!
}
