// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaInterface("kotlin.reflect.KDeclarationContainer")
public struct KDeclarationContainer {
  @JavaMethod
  public func getMembers() -> JavaCollection<KCallable<JavaObject>>!
}
