// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KFunction {
  @JavaClass("kotlin.reflect.KFunction$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<KFunction.DefaultImpls> {
  @JavaStaticMethod
  public func isSuspend$annotations()

  @JavaStaticMethod
  public func isExternal$annotations()

  @JavaStaticMethod
  public func isInfix$annotations()

  @JavaStaticMethod
  public func isInline$annotations()

  @JavaStaticMethod
  public func isOperator$annotations()
}
