// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaLangReflect
import CSwiftJavaJNI
import JavaUtil
import JavaLangUtil

@JavaInterface("kotlin.reflect.KFunction", extends: KCallable<JavaObject>.self, Function<JavaObject>.self)
public struct KFunction<R: AnyJavaObject> {
  @JavaMethod
  public func isInline() -> Bool

  @JavaMethod
  public func isExternal() -> Bool

  @JavaMethod
  public func isOperator() -> Bool

  @JavaMethod
  public func isInfix() -> Bool

  @JavaMethod
  public func isSuspend() -> Bool

  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getTypeParameters() -> List<KTypeParameter>!

  @JavaMethod
  public func isFinal() -> Bool

  @JavaMethod
  public func getReturnType() -> KType!

  @JavaMethod
  public func isOpen() -> Bool

  @JavaMethod
  public func getParameters() -> List<KParameter>!

  @JavaMethod
  public func isAbstract() -> Bool

  @JavaMethod
  public func call(_ arg0: [JavaObject?]) -> JavaObject!

  @JavaMethod
  public func callBy(_ arg0: Map<KParameter, JavaObject>?) -> JavaObject!

  @JavaMethod
  public func getVisibility() -> KVisibility!

  @JavaMethod
  public func getAnnotations() -> List<Annotation>!
}
