// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import CSwiftJavaJNI

@JavaInterface("kotlin.jvm.internal.markers.KMutableIterator", extends: KMappedMarker.self)
public struct KMutableIterator {

}
