// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitReflection
import JavaRuntime
import JavaUtil

@JavaInterface("kotlin.reflect.KMutableProperty2", extends: KProperty2<JavaObject, JavaObject, JavaObject>.self, KMutableProperty<JavaObject>.self)
public struct KMutableProperty2<D: AnyJavaObject, E: AnyJavaObject, V: AnyJavaObject> {
  @JavaMethod
  public func getSetter() -> KMutableProperty2.Setter<JavaObject, JavaObject, JavaObject>!

  @JavaMethod
  public func getSetter() -> KMutableProperty.Setter<JavaObject>!

  @JavaMethod
  public func set(_ arg0: JavaObject?, _ arg1: JavaObject?, _ arg2: JavaObject?)

  @JavaMethod
  public func getGetter() -> KProperty2.Getter<JavaObject, JavaObject, JavaObject>!

  @JavaMethod
  public func getGetter() -> KProperty.Getter<JavaObject>!

  @JavaMethod
  public func getDelegate(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  public func get(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  public func isLateinit() -> Bool

  @JavaMethod
  public func isConst() -> Bool

  @JavaMethod
  public func callBy(_ arg0: Map<KParameter, JavaObject>?) -> JavaObject!

  @JavaMethod
  public func getVisibility() -> KVisibility!

  @JavaMethod
  public func isSuspend() -> Bool

  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getTypeParameters() -> List<KTypeParameter>!

  @JavaMethod
  public func isFinal() -> Bool

  @JavaMethod
  public func getReturnType() -> KType!

  @JavaMethod
  public func isOpen() -> Bool

  @JavaMethod
  public func getParameters() -> List<KParameter>!

  @JavaMethod
  public func isAbstract() -> Bool

  @JavaMethod
  public func call(_ arg0: [JavaObject?]) -> JavaObject!

  @JavaMethod
  public func getAnnotations() -> List<Annotation>!

  @JavaMethod
  public func invoke(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!
}
