// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KMutableProperty2 {
  @JavaClass("kotlin.reflect.KMutableProperty2$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<KMutableProperty2.DefaultImpls> {
  @JavaStaticMethod
  public func getSetter$annotations()
}
