// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KMutableProperty1 {
  @JavaClass("kotlin.reflect.KMutableProperty1$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<KMutableProperty1.DefaultImpls> {
  @JavaStaticMethod
  public func getSetter$annotations()
}
