// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.jvm.internal.markers.KMutableIterator", extends: KMappedMarker.self)
public struct KMutableIterator {

}
