// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.KotlinVersionCurrentValue")
open class KotlinVersionCurrentValue: JavaObject {

}
extension JavaClass<KotlinVersionCurrentValue> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: KotlinVersionCurrentValue!

  @JavaStaticMethod
  public func get() -> KotlinVersion!
}
