// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime
import JavaUtil

@JavaClass("kotlin.random.KotlinRandom")
open class KotlinRandom: Random {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Random?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func next(_ arg0: Int32) -> Int32

  @JavaMethod
  open override func nextDouble() -> Double

  @JavaMethod
  open override func nextInt(_ arg0: Int32) -> Int32

  @JavaMethod
  open override func nextInt() -> Int32

  @JavaMethod
  open override func nextBytes(_ arg0: [Int8])

  @JavaMethod
  open override func setSeed(_ arg0: Int64)

  @JavaMethod
  open override func nextLong() -> Int64

  @JavaMethod
  open override func nextBoolean() -> Bool

  @JavaMethod
  open override func nextFloat() -> Float

  @JavaMethod
  open func getImpl() -> Random!
}
