// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitReflection
import JavaRuntime

@JavaInterface("kotlin.reflect.KParameter", extends: KAnnotatedElement.self)
public struct KParameter {
  @JavaMethod
  public func getKind() -> KParameter.Kind!

  @JavaMethod
  public func isOptional() -> Bool

  @JavaMethod
  public func isVararg() -> Bool

  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getType() -> KType!

  @JavaMethod
  public func getIndex() -> Int32

  @JavaMethod
  public func getAnnotations() -> List<Annotation>!
}
