// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KParameter {
  @JavaClass("kotlin.reflect.KParameter$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<KParameter.DefaultImpls> {
  @JavaStaticMethod
  public func isVararg$annotations()
}
