// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitReflection
import JavaRuntime

@JavaInterface("kotlin.reflect.KProperty", extends: KCallable<JavaObject>.self)
public struct KProperty<V: AnyJavaObject> {
  @JavaMethod
  public func getGetter() -> KProperty.Getter<JavaObject>!

  @JavaMethod
  public func isLateinit() -> Bool

  @JavaMethod
  public func isConst() -> Bool

  @JavaMethod
  public func getVisibility() -> KVisibility!

  @JavaMethod
  public func isSuspend() -> Bool

  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getTypeParameters() -> List<KTypeParameter>!

  @JavaMethod
  public func isFinal() -> Bool

  @JavaMethod
  public func getReturnType() -> KType!

  @JavaMethod
  public func isOpen() -> Bool

  @JavaMethod
  public func getParameters() -> List<KParameter>!

  @JavaMethod
  public func isAbstract() -> Bool

  @JavaMethod
  public func call(_ arg0: [JavaObject?]) -> JavaObject!

  @JavaMethod
  public func getAnnotations() -> List<Annotation>!
}
