// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KProperty2 {
  @JavaClass("kotlin.reflect.KProperty2$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<KProperty2.DefaultImpls> {
  @JavaStaticMethod
  public func getGetter$annotations()
}
