// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaLangReflect
import CSwiftJavaJNI

@JavaInterface("kotlin.reflect.KProperty1", extends: KProperty<JavaObject>.self, Function1<JavaObject, JavaObject>.self)
public struct KProperty1<T: AnyJavaObject, V: AnyJavaObject> {
    
  @JavaMethod
  public func getDelegate(_ arg0: JavaObject?) -> JavaObject!

  @JavaMethod
  public func getGetter() -> KProperty1<JavaObject, JavaObject>.Getter!

  @JavaMethod
  public func get(_ arg0: JavaObject?) -> JavaObject!

  @JavaMethod
  public func isLateinit() -> Bool

  @JavaMethod
  public func isConst() -> Bool

  @JavaMethod
  public func getVisibility() -> KVisibility!

  @JavaMethod
  public func isSuspend() -> Bool

  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getTypeParameters() -> List<KTypeParameter>!

  @JavaMethod
  public func isFinal() -> Bool

  @JavaMethod
  public func getReturnType() -> KType!

  @JavaMethod
  public func isOpen() -> Bool

  @JavaMethod
  public func getParameters() -> List<KParameter>!

  @JavaMethod
  public func isAbstract() -> Bool

  @JavaMethod
  public func call(_ arg0: [JavaObject?]) -> JavaObject!

  @JavaMethod
  public func getAnnotations() -> List<Annotation>!

  @JavaMethod
  public func invoke(_ arg0: JavaObject?) -> JavaObject!
}
