// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitReflection
import JavaRuntime

extension KProperty1 {
  @JavaInterface("kotlin.reflect.KProperty1$Getter", extends: KProperty.Getter<JavaObject>.self, Function1<JavaObject, JavaObject>.self)
  public struct Getter<T: AnyJavaObject, V: AnyJavaObject> {
  @JavaMethod
  public func getProperty() -> KProperty<JavaObject>!

  @JavaMethod
  public func isSuspend() -> Bool

  @JavaMethod
  public func isInline() -> Bool

  @JavaMethod
  public func isExternal() -> Bool

  @JavaMethod
  public func isOperator() -> Bool

  @JavaMethod
  public func isInfix() -> Bool

  @JavaMethod
  public func getVisibility() -> KVisibility!

  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getTypeParameters() -> List<KTypeParameter>!

  @JavaMethod
  public func isFinal() -> Bool

  @JavaMethod
  public func getReturnType() -> KType!

  @JavaMethod
  public func isOpen() -> Bool

  @JavaMethod
  public func getParameters() -> List<KParameter>!

  @JavaMethod
  public func isAbstract() -> Bool

  @JavaMethod
  public func call(_ arg0: [JavaObject?]) -> JavaObject!

  @JavaMethod
  public func getAnnotations() -> List<Annotation>!

  @JavaMethod
  public func invoke(_ arg0: JavaObject?) -> JavaObject!
  }
}
