// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import JavaLangReflect
import CSwiftJavaJNI

extension KProperty {
  @JavaInterface("kotlin.reflect.KProperty$Getter", extends: KProperty.Accessor<JavaObject>.self, KFunction<JavaObject>.self)
  public struct Getter {
  @JavaMethod
  public func getProperty() -> KProperty<JavaObject>!

  @JavaMethod
  public func isSuspend() -> Bool

  @JavaMethod
  public func isInline() -> Bool

  @JavaMethod
  public func isExternal() -> Bool

  @JavaMethod
  public func isOperator() -> Bool

  @JavaMethod
  public func isInfix() -> Bool

  @JavaMethod
  public func getVisibility() -> KVisibility!

  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getTypeParameters() -> List<KTypeParameter>!

  @JavaMethod
  public func isFinal() -> Bool

  @JavaMethod
  public func getReturnType() -> KType!

  @JavaMethod
  public func isOpen() -> Bool

  @JavaMethod
  public func getParameters() -> List<KParameter>!

  @JavaMethod
  public func isAbstract() -> Bool

  @JavaMethod
  public func call(_ arg0: [JavaObject?]) -> JavaObject!

  @JavaMethod
  public func getAnnotations() -> List<Annotation>!
  }
}
