// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KType {
  @JavaClass("kotlin.reflect.KType$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<KType.DefaultImpls> {
  @JavaStaticMethod
  public func getArguments$annotations()

  @JavaStaticMethod
  public func getClassifier$annotations()
}
