// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KTypeProjection {
  @JavaClass("kotlin.reflect.KTypeProjection$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getSTAR() -> KTypeProjection!

  @JavaMethod
  open func invariant(_ arg0: KType?) -> KTypeProjection!

  @JavaMethod
  open func contravariant(_ arg0: KType?) -> KTypeProjection!

  @JavaMethod
  open func covariant(_ arg0: KType?) -> KTypeProjection!
  }
}
extension JavaClass<KTypeProjection.Companion> {
  @JavaStaticMethod
  public func getStar$annotations()
}
