// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaInterface("kotlin.reflect.KTypeParameter", extends: KClassifier.self)
public struct KTypeParameter {
  @JavaMethod
  public func getName() -> String

  @JavaMethod
  public func getUpperBounds() -> List<KType>!

  @JavaMethod
  public func getVariance() -> KVariance!

  @JavaMethod
  public func isReified() -> Bool
}
