// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension KTypeProjection {
  @JavaClass("kotlin.reflect.KTypeProjection$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}