// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.LateinitKt")
open class LateinitKt: JavaObject {

}
extension JavaClass<LateinitKt> {
  @JavaStaticMethod
  public func isInitialized$annotations(_ arg0: KProperty0?)
}
