// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.Lazy")
public struct Lazy<T: AnyJavaObject> {
  @JavaMethod
  public func getValue() -> JavaObject!

  @JavaMethod
  public func isInitialized() -> Bool
}
