// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension LazyKt__LazyJVMKt {
  @JavaClass("kotlin.LazyKt__LazyJVMKt$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}