// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.LazyKt__LazyJVMKt")
open class LazyKt__LazyJVMKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<LazyKt__LazyJVMKt> {
  @JavaStaticMethod
  public func lazy(_ arg0: Function0<JavaObject>?) -> Lazy<JavaObject>!

  @JavaStaticMethod
  public func lazy(_ arg0: JavaObject?, _ arg1: Function0<JavaObject>?) -> Lazy<JavaObject>!

  @JavaStaticMethod
  public func lazy(_ arg0: LazyThreadSafetyMode?, _ arg1: Function0<JavaObject>?) -> Lazy<JavaObject>!
}
