// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.io.LinesSequence", implements: Sequence<JavaString>.self)
open class LinesSequence: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: BufferedReader?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func iterator() -> JavaIterator<JavaString>!
}
extension JavaClass<LinesSequence> {
  @JavaStaticMethod
  public func access$getReader$p(_ arg0: LinesSequence?) -> BufferedReader!
}
