// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.LineReader")
open class LineReader: JavaObject {
  @JavaMethod
  open func readLine(_ arg0: InputStream?, _ arg1: Charset?) -> String
}
extension JavaClass<LineReader> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: LineReader!
}
