// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.io.path.LinkFollowing")
open class LinkFollowing: JavaObject {

}
extension JavaClass<LinkFollowing> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: LinkFollowing!
}
