// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaKitCollection
import JavaRuntime

extension ListBuilder {
  @JavaClass("kotlin.collections.builders.ListBuilder$BuilderSubList", implements: List<JavaObject>.self, RandomAccess.self, Serializable.self, KMutableList.self)
  open class BuilderSubList<E: AnyJavaObject>: AbstractMutableList {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [JavaObject?], _ arg1: Int32, _ arg2: Int32, _ arg3: ListBuilder.BuilderSubList<JavaObject>?, _ arg4: ListBuilder<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func removeAt(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  open func remove(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func get(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func indexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open func clear()

  @JavaMethod
  open func lastIndexOf(_ arg0: JavaObject?) -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func add(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func add(_ arg0: Int32, _ arg1: JavaObject?)

  @JavaMethod
  open func subList(_ arg0: Int32, _ arg1: Int32) -> List<JavaObject>!

  @JavaMethod
  open func toArray() -> [JavaObject?]

  @JavaMethod
  open func toArray(_ arg0: [JavaObject?]) -> [JavaObject?]

  @JavaMethod
  open func iterator() -> JavaIterator<JavaObject>!

  @JavaMethod
  open func addAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func addAll(_ arg0: Int32, _ arg1: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open override func set(_ arg0: Int32, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  open override func getSize() -> Int32

  @JavaMethod
  open func removeAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func retainAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func listIterator() -> ListIterator<JavaObject>!

  @JavaMethod
  open func listIterator(_ arg0: Int32) -> ListIterator<JavaObject>!
  }
}
extension JavaClass {
  @JavaStaticMethod
  public func access$getModCount$p$s1462993667<E: AnyJavaObject>(_ arg0: ListBuilder.BuilderSubList?) -> Int32 where ObjectType == ListBuilder.BuilderSubList<E>

  @JavaStaticMethod
  public func access$getOffset$p<E: AnyJavaObject>(_ arg0: ListBuilder.BuilderSubList?) -> Int32 where ObjectType == ListBuilder.BuilderSubList<E>

  @JavaStaticMethod
  public func access$getRoot$p<E: AnyJavaObject>(_ arg0: ListBuilder.BuilderSubList?) -> ListBuilder! where ObjectType == ListBuilder.BuilderSubList<E>

  @JavaStaticMethod
  public func access$getLength$p<E: AnyJavaObject>(_ arg0: ListBuilder.BuilderSubList?) -> Int32 where ObjectType == ListBuilder.BuilderSubList<E>

  @JavaStaticMethod
  public func access$getBacking$p<E: AnyJavaObject>(_ arg0: ListBuilder.BuilderSubList?) -> [JavaObject?] where ObjectType == ListBuilder.BuilderSubList<E>
}
