// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension ListBuilder {
  @JavaClass("kotlin.collections.builders.ListBuilder$Itr", implements: ListIterator<JavaObject>.self, KMutableListIterator.self)
  open class Itr<E: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ListBuilder<JavaObject>?, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove()

  @JavaMethod
  open func add(_ arg0: JavaObject?)

  @JavaMethod
  open func hasNext() -> Bool

  @JavaMethod
  open func next() -> JavaObject!

  @JavaMethod
  open func set(_ arg0: JavaObject?)

  @JavaMethod
  open func nextIndex() -> Int32

  @JavaMethod
  open func previousIndex() -> Int32

  @JavaMethod
  open func hasPrevious() -> Bool

  @JavaMethod
  open func previous() -> JavaObject!
  }
}
