// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ListBuilder {
  @JavaClass("kotlin.collections.builders.ListBuilder$Companion")
  open class Companion: JavaObject {

  }
}
