// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.LocalVariableReferencesKt")
open class LocalVariableReferencesKt: JavaObject {

}
extension JavaClass<LocalVariableReferencesKt> {
  @JavaStaticMethod
  public func access$notSupportedError() -> JavaVoid!
}
