// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension LongProgression {
  @JavaClass("kotlin.ranges.LongProgression$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func fromClosedRange(_ arg0: Int64, _ arg1: Int64, _ arg2: Int64) -> LongProgression!
  }
}
