// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.ranges.LongRange", implements: ClosedRange<JavaLong>.self, OpenEndRange<JavaLong>.self)
open class LongRange: LongProgression {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int64, _ arg1: Int64, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open override func isEmpty() -> Bool

  @JavaMethod
  open func contains(_ arg0: Comparable?) -> Bool

  @JavaMethod
  open func contains(_ arg0: Int64) -> Bool

  @JavaMethod
  open func getEndExclusive() -> JavaLong!

  @JavaMethod
  open func getEndExclusive() -> Comparable!

  @JavaMethod
  open func getStart() -> JavaLong!

  @JavaMethod
  open func getStart() -> Comparable!

  @JavaMethod
  open func getEndInclusive() -> JavaLong!

  @JavaMethod
  open func getEndInclusive() -> Comparable!
}
extension JavaClass<LongRange> {
  @JavaStaticField(isFinal: true)
  public var Companion: LongRange.Companion!

  @JavaStaticField(isFinal: true)
  public var Companion: LongProgression.Companion!

  @JavaStaticMethod
  public func getEndExclusive$annotations()

  @JavaStaticMethod
  public func access$getEMPTY$cp() -> LongRange!
}
