// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaLang
import JavaRuntime

@JavaClass("kotlin.ranges.LongProgression", implements: Iterable<JavaLong>.self, KMappedMarker.self)
open class LongProgression: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int64, _ arg1: Int64, _ arg2: Int64, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func iterator() -> LongIterator!

  @JavaMethod
  open func iterator() -> JavaIterator!

  @JavaMethod
  open func getFirst() -> Int64

  @JavaMethod
  open func getLast() -> Int64

  @JavaMethod
  open func getStep() -> Int64
}
extension JavaClass<LongProgression> {
  @JavaStaticField(isFinal: true)
  public var Companion: LongProgression.Companion!
}
