// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime
import JavaUtil

extension MapBuilder {
  @JavaClass("kotlin.collections.builders.MapBuilder$EntryRef", implements: Map.Entry<JavaObject, JavaObject>.self, KMutableMap.Entry.self)
  open class EntryRef<K: AnyJavaObject, V: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: MapBuilder<JavaObject, JavaObject>?, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getValue() -> JavaObject!

  @JavaMethod
  open func getKey() -> JavaObject!

  @JavaMethod
  open func setValue(_ arg0: JavaObject?) -> JavaObject!
  }
}
