// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.builders.MapBuilderValues", implements: JavaCollection<JavaObject>.self)
open class MapBuilderValues<V: AnyJavaObject>: AbstractMutableCollection {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: MapBuilder<JavaObject, JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getBacking() -> MapBuilder<JavaObject, JavaObject>!

  @JavaMethod
  open func remove(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func clear()

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open override func add(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func iterator() -> JavaIterator<JavaObject>!

  @JavaMethod
  open func contains(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open func addAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open override func getSize() -> Int32

  @JavaMethod
  open func removeAll(_ arg0: JavaCollection<JavaObject>?) -> Bool

  @JavaMethod
  open func retainAll(_ arg0: JavaCollection<JavaObject>?) -> Bool
}
