// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension MapBuilder {
  @JavaClass("kotlin.collections.builders.MapBuilder$Itr")
  open class Itr<K: AnyJavaObject, V: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: MapBuilder<JavaObject, JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func initNext$kotlin_stdlib()

  @JavaMethod
  open func getMap$kotlin_stdlib() -> MapBuilder<JavaObject, JavaObject>!

  @JavaMethod
  open func getIndex$kotlin_stdlib() -> Int32

  @JavaMethod
  open func setIndex$kotlin_stdlib(_ arg0: Int32)

  @JavaMethod
  open func getLastIndex$kotlin_stdlib() -> Int32

  @JavaMethod
  open func setLastIndex$kotlin_stdlib(_ arg0: Int32)

  @JavaMethod
  open func checkForComodification$kotlin_stdlib()

  @JavaMethod
  open func remove()

  @JavaMethod
  open func hasNext() -> Bool
  }
}
