// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension MapBuilder {
  @JavaClass("kotlin.collections.builders.MapBuilder$KeysItr", implements: JavaIterator<JavaObject>.self)
  open class KeysItr<K: AnyJavaObject, V: AnyJavaObject>: MapBuilder.Itr {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: MapBuilder<JavaObject, JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func next() -> JavaObject!
  }
}
