// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.collections.MapsKt___MapsJvmKt")
open class MapsKt___MapsJvmKt: MapsKt__MapsKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
