// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.collections.MapsKt__MapsJVMKt")
open class MapsKt__MapsJVMKt: MapsKt__MapWithDefaultKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<MapsKt__MapsJVMKt> {
  @JavaStaticMethod
  public func mapCapacity(_ arg0: Int32) -> Int32
}
