// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension MatchResult {
  @JavaClass("kotlin.text.MatchResult$Destructured")
  open class Destructured: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: MatchResult?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func toList() -> List<JavaString>!

  @JavaMethod
  open func getMatch() -> MatchResult!
  }
}
