// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.text.MatcherMatchResult", implements: MatchResult.self)
open class MatcherMatchResult: JavaObject {
  @JavaMethod
  open func getGroupValues() -> List<JavaString>!

  @JavaMethod
  open func getRange() -> IntRange!

  @JavaMethod
  open func getGroups() -> MatchGroupCollection!

  @JavaMethod
  open func getDestructured() -> MatchResult.Destructured!

  @JavaMethod
  open func getValue() -> String

  @JavaMethod
  open func next() -> MatchResult!
}
