// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Metadata {
  @JavaClass("kotlin.Metadata$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<Metadata.DefaultImpls> {
  @JavaStaticMethod
  public func bv$annotations()

  @JavaStaticMethod
  public func xi$annotations()

  @JavaStaticMethod
  public func pn$annotations()
}
