// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.jvm.internal.ModuleNameRetriever")
open class ModuleNameRetriever: JavaObject {
  @JavaMethod
  open func getModuleName(_ arg0: BaseContinuationImpl?) -> String
}
extension JavaClass<ModuleNameRetriever> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: ModuleNameRetriever!
}
