// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

extension ModuleNameRetriever {
  @JavaClass("kotlin.coroutines.jvm.internal.ModuleNameRetriever$Cache")
  open class Cache: JavaObject {
  @JavaField(isFinal: true)
  public var getModuleMethod: Method!

  @JavaField(isFinal: true)
  public var getDescriptorMethod: Method!

  @JavaField(isFinal: true)
  public var nameMethod: Method!

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Method?, _ arg1: Method?, _ arg2: Method?, environment: JNIEnvironment? = nil)
  }
}
