// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.MonoTimeSourceKt")
open class MonoTimeSourceKt: JavaObject {

}
extension JavaClass<MonoTimeSourceKt> {
  @JavaStaticMethod
  public func ValueTimeMarkReading$annotations()
}
