// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.MovingSubList", implements: RandomAccess.self)
open class MovingSubList<E: AnyJavaObject>: AbstractList {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: List<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func get(_ arg0: Int32) -> JavaObject!

  @JavaMethod
  open override func getSize() -> Int32

  @JavaMethod
  open func move(_ arg0: Int32, _ arg1: Int32)
}
extension JavaClass {
  @JavaStaticField(isFinal: true)
  public var Companion: AbstractList.Companion!
}
