// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.comparisons.NaturalOrderComparator")
open class NaturalOrderComparator: JavaObject {
  @JavaMethod
  open func compare(_ arg0: Comparable?, _ arg1: Comparable?) -> Int32

  @JavaMethod
  open func compare(_ arg0: JavaObject?, _ arg1: JavaObject?) -> Int32
}
extension JavaClass<NaturalOrderComparator> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: NaturalOrderComparator!
}
