// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.properties.NotNullVar", implements: ReadWriteProperty<JavaObject, JavaObject>.self)
open class NotNullVar<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open func getValue(_ arg0: JavaObject?, _ arg1: KProperty<JavaObject>?) -> JavaObject!

  @JavaMethod
  open func setValue(_ arg0: JavaObject?, _ arg1: KProperty<JavaObject>?, _ arg2: JavaObject?)
}
