// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.NumbersKt__FloorDivModKt")
open class NumbersKt__FloorDivModKt: NumbersKt__BigIntegersKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
