// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.NumbersKt__NumbersKt")
open class NumbersKt__NumbersKt: NumbersKt__NumbersJVMKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<NumbersKt__NumbersKt> {
  @JavaStaticMethod
  public func rotateLeft(_ arg0: Int8, _ arg1: Int32) -> Int8

  @JavaStaticMethod
  public func rotateLeft(_ arg0: Int16, _ arg1: Int32) -> Int16

  @JavaStaticMethod
  public func rotateRight(_ arg0: Int8, _ arg1: Int32) -> Int8

  @JavaStaticMethod
  public func rotateRight(_ arg0: Int16, _ arg1: Int32) -> Int16
}
