// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.path.OnErrorResult")
open class OnErrorResult: JavaObject {
  public enum OnErrorResultCases: Equatable {
    case SKIP_SUBTREE
    case TERMINATE
  }

  public var enumValue: OnErrorResultCases! {
    let classObj = self.javaClass
    if self.equals(classObj.SKIP_SUBTREE?.as(JavaObject.self)) {
      return OnErrorResultCases.SKIP_SUBTREE
    } else if self.equals(classObj.TERMINATE?.as(JavaObject.self)) {
      return OnErrorResultCases.TERMINATE
    } else {
      return nil
    }
  }

  public convenience init(_ enumValue: OnErrorResultCases, environment: JNIEnvironment? = nil) {
    let _environment = if let environment {
      environment
    } else {
      try! JavaVirtualMachine.shared().environment()
    }
    let classObj = try! JavaClass<OnErrorResult>(environment: _environment)
    switch enumValue {
      case .SKIP_SUBTREE:
        if let SKIP_SUBTREE = classObj.SKIP_SUBTREE {
          self.init(javaHolder: SKIP_SUBTREE.javaHolder)
        } else {
          fatalError("Enum value SKIP_SUBTREE was unexpectedly nil, please re-run Java2Swift on the most updated Java class")
        }
      case .TERMINATE:
        if let TERMINATE = classObj.TERMINATE {
          self.init(javaHolder: TERMINATE.javaHolder)
        } else {
          fatalError("Enum value TERMINATE was unexpectedly nil, please re-run Java2Swift on the most updated Java class")
        }
    }
  }
}
extension JavaClass<OnErrorResult> {
  @JavaStaticField(isFinal: true)
  public var SKIP_SUBTREE: OnErrorResult!

  @JavaStaticField(isFinal: true)
  public var TERMINATE: OnErrorResult!

  @JavaStaticMethod
  public func values() -> [OnErrorResult?]

  @JavaStaticMethod
  public func valueOf(_ arg0: String) -> OnErrorResult!

  @JavaStaticMethod
  public func getEntries() -> EnumEntries<OnErrorResult>!
}
