// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.ranges.OpenEndDoubleRange", implements: OpenEndRange<JavaDouble>.self)
open class OpenEndDoubleRange: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Double, _ arg1: Double, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getStart() -> JavaDouble!

  @JavaMethod
  open func getEndExclusive() -> JavaDouble!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func contains(_ arg0: Double) -> Bool
}
