// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.ranges.OpenEndFloatRange", implements: OpenEndRange<JavaFloat>.self)
open class OpenEndFloatRange: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Float, _ arg1: Float, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getStart() -> JavaFloat!

  @JavaMethod
  open func getEndExclusive() -> JavaFloat!

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func contains(_ arg0: Float) -> Bool
}
