// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

extension OpenEndRange {
  @JavaClass("kotlin.ranges.OpenEndRange$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<OpenEndRange.DefaultImpls> {
  @JavaStaticMethod
  public func isEmpty(_ arg0: OpenEndRange<Comparable<JavaObject>>?) -> Bool

  @JavaStaticMethod
  public func contains(_ arg0: OpenEndRange<Comparable<JavaObject>>?, _ arg1: Comparable<JavaObject>?) -> Bool
}
