// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

@JavaInterface("kotlin.OptIn", extends: Annotation.self)
public struct OptIn {
  @JavaMethod
  public func markerClass() -> [JavaClass<Annotation>?]

  @JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func toString() -> String

  @JavaMethod
  public func hashCode() -> Int32

  @JavaMethod
  public func annotationType() -> JavaClass<Annotation>!
}
