// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.path.PathTreeWalkKt")
open class PathTreeWalkKt: JavaObject {

}
extension JavaClass<PathTreeWalkKt> {
  @JavaStaticMethod
  public func access$createsCycle(_ arg0: PathNode?) -> Bool
}
