// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaKitIO
import JavaRuntime

@JavaClass("kotlin.io.path.PathsKt__PathUtilsKt")
open class PathsKt__PathUtilsKt: PathsKt__PathRecursiveFunctionsKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<PathsKt__PathUtilsKt> {
  @JavaStaticMethod
  public func getName(_ arg0: Path?) -> String

  @JavaStaticMethod
  public func walk(_ arg0: Path?, _ arg1: [PathWalkOption?]) -> Sequence<Path>!

  @JavaStaticMethod
  public func getExtension(_ arg0: Path?) -> String

  @JavaStaticMethod
  public func getNameWithoutExtension$annotations(_ arg0: Path?)

  @JavaStaticMethod
  public func getInvariantSeparatorsPathString$annotations(_ arg0: Path?)

  @JavaStaticMethod
  public func getInvariantSeparatorsPath$annotations(_ arg0: Path?)

  @JavaStaticMethod
  public func visitFileTree$default(_ arg0: Path?, _ arg1: Int32, _ arg2: Bool, _ arg3: Function1?, _ arg4: Int32, _ arg5: JavaObject?)

  @JavaStaticMethod
  public func getExtension$annotations(_ arg0: Path?)

  @JavaStaticMethod
  public func getPathString$annotations(_ arg0: Path?)

  @JavaStaticMethod
  public func getInvariantSeparatorsPathString(_ arg0: Path?) -> String

  @JavaStaticMethod
  public func listDirectoryEntries(_ arg0: Path?, _ arg1: String) throws -> List<Path>!

  @JavaStaticMethod
  public func listDirectoryEntries$default(_ arg0: Path?, _ arg1: String, _ arg2: Int32, _ arg3: JavaObject?) throws -> List!

  @JavaStaticMethod
  public func fileAttributeViewNotAvailable(_ arg0: Path?, _ arg1: JavaClass<JavaObject>?) -> JavaVoid!

  @JavaStaticMethod
  public func getName$annotations(_ arg0: Path?)

  @JavaStaticMethod
  public func getNameWithoutExtension(_ arg0: Path?) -> String

  @JavaStaticMethod
  public func relativeTo(_ arg0: Path?, _ arg1: Path?) -> Path!

  @JavaStaticMethod
  public func relativeToOrSelf(_ arg0: Path?, _ arg1: Path?) -> Path!

  @JavaStaticMethod
  public func relativeToOrNull(_ arg0: Path?, _ arg1: Path?) -> Path!

  @JavaStaticMethod
  public func visitFileTree(_ arg0: Path?, _ arg1: Int32, _ arg2: Bool, _ arg3: Function1<JavaObject, Unit>?)
}
