// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension PathsKt__PathRecursiveFunctionsKt {
  @JavaClass("kotlin.io.path.PathsKt__PathRecursiveFunctionsKt$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}
