// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime
import JavaUtil

@JavaClass("kotlin.random.PlatformRandomKt")
open class PlatformRandomKt: JavaObject {

}
extension JavaClass<PlatformRandomKt> {
  @JavaStaticMethod
  public func asJavaRandom(_ arg0: Random?) -> Random!

  @JavaStaticMethod
  public func asKotlinRandom(_ arg0: Random?) -> Random!

  @JavaStaticMethod
  public func doubleFromParts(_ arg0: Int32, _ arg1: Int32) -> Double
}
