// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.random.jdk8.PlatformThreadLocalRandom")
open class PlatformThreadLocalRandom: AbstractPlatformRandom {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func nextDouble(_ arg0: Double) -> Double

  @JavaMethod
  open override func nextInt(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaMethod
  open override func nextLong(_ arg0: Int64, _ arg1: Int64) -> Int64

  @JavaMethod
  open override func nextLong(_ arg0: Int64) -> Int64
}
extension JavaClass<PlatformThreadLocalRandom> {
  @JavaStaticField(isFinal: true)
  public var Default: Random.Default!
}
