// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.PrimitiveSpreadBuilder")
open class PrimitiveSpreadBuilder<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getPosition() -> Int32

  @JavaMethod
  open func setPosition(_ arg0: Int32)

  @JavaMethod
  open func addSpread(_ arg0: JavaObject?)

  @JavaMethod
  open func size() -> Int32

  @JavaMethod
  open func toArray(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  open func getSize(_ arg0: JavaObject?) -> Int32
}
