// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.PropertyReference2", implements: KProperty2.self)
open class PropertyReference2: PropertyReference {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaClass?, _ arg1: String, _ arg2: String, _ arg3: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func invoke(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  open override func computeReflected() -> KCallable!

  @JavaMethod
  open func getDelegate(_ arg0: JavaObject?, _ arg1: JavaObject?) -> JavaObject!

  @JavaMethod
  open func getGetter() -> KProperty.Getter!

  @JavaMethod
  open func getGetter() -> KProperty2.Getter!
}
extension JavaClass<PropertyReference2> {
  @JavaStaticField(isFinal: true)
  public var NO_RECEIVER: JavaObject!
}
