// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.PropertyReference1", implements: KProperty1.self)
open class PropertyReference1: PropertyReference {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaObject?, _ arg1: JavaClass?, _ arg2: String, _ arg3: String, _ arg4: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaObject?, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getGetter() -> KProperty1.Getter!

  @JavaMethod
  open func getGetter() -> KProperty.Getter!

  @JavaMethod
  open override func computeReflected() -> KCallable!

  @JavaMethod
  open func getDelegate(_ arg0: JavaObject?) -> JavaObject!

  @JavaMethod
  open func invoke(_ arg0: JavaObject?) -> JavaObject!
}
extension JavaClass<PropertyReference1> {
  @JavaStaticField(isFinal: true)
  public var NO_RECEIVER: JavaObject!
}
