// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.jvm.internal.PropertyReference0Impl")
open class PropertyReference0Impl: PropertyReference0 {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaObject?, _ arg1: JavaClass?, _ arg2: String, _ arg3: String, _ arg4: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: JavaClass?, _ arg1: String, _ arg2: String, _ arg3: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: KDeclarationContainer?, _ arg1: String, _ arg2: String, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func get() -> JavaObject!
}
extension JavaClass<PropertyReference0Impl> {
  @JavaStaticField(isFinal: true)
  public var NO_RECEIVER: JavaObject!
}
