// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

extension Random.Default {
  @JavaClass("kotlin.random.Random$Default$Serialized", implements: Serializable.self)
  open class Serialized: JavaObject {

  }
}
extension JavaClass<Random.Default.Serialized> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: Random.Default.Serialized!
}
