// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.random.RandomKt")
open class RandomKt: JavaObject {

}
extension JavaClass<RandomKt> {
  @JavaStaticMethod
  public func takeUpperBits(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func checkRangeBounds(_ arg0: Int32, _ arg1: Int32)

  @JavaStaticMethod
  public func checkRangeBounds(_ arg0: Int64, _ arg1: Int64)

  @JavaStaticMethod
  public func checkRangeBounds(_ arg0: Double, _ arg1: Double)

  @JavaStaticMethod
  public func fastLog2(_ arg0: Int32) -> Int32

  @JavaStaticMethod
  public func Random(_ arg0: Int32) -> Random!

  @JavaStaticMethod
  public func Random(_ arg0: Int64) -> Random!

  @JavaStaticMethod
  public func boundsErrorMessage(_ arg0: JavaObject?, _ arg1: JavaObject?) -> String

  @JavaStaticMethod
  public func nextInt(_ arg0: Random?, _ arg1: IntRange?) -> Int32

  @JavaStaticMethod
  public func nextLong(_ arg0: Random?, _ arg1: LongRange?) -> Int64
}
