// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.properties.ReadOnlyProperty")
public struct ReadOnlyProperty<T: AnyJavaObject, V: AnyJavaObject> {
  @JavaMethod
  public func getValue(_ arg0: JavaObject?, _ arg1: KProperty<JavaObject>?) -> JavaObject!
}
