// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

extension Ref {
  @JavaClass("kotlin.jvm.internal.Ref$ObjectRef", implements: Serializable.self)
  open class ObjectRef<T: AnyJavaObject>: JavaObject {
  @JavaField(isFinal: false)
  public var element: JavaObject!

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func toString() -> String
  }
}
