// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

extension Ref {
  @JavaClass("kotlin.jvm.internal.Ref$ShortRef", implements: Serializable.self)
  open class ShortRef: JavaObject {
  @JavaField(isFinal: false)
  public var element: Int16

  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func toString() -> String
  }
}
