// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Regex {
  @JavaClass("kotlin.text.Regex$Serialized")
  open class Serialized: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: String, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getPattern() -> String

  @JavaMethod
  open func getFlags() -> Int32
  }
}
extension JavaClass<Regex.Serialized> {
  @JavaStaticField(isFinal: true)
  public var Companion: Regex.Serialized.Companion!
}
