// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension Regex {
  @JavaClass("kotlin.text.Regex$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func escape(_ arg0: String) -> String

  @JavaMethod
  open func fromLiteral(_ arg0: String) -> Regex!

  @JavaMethod
  open func escapeReplacement(_ arg0: String) -> String
  }
}
extension JavaClass<Regex.Companion> {
  @JavaStaticMethod
  public func access$ensureUnicodeCase(_ arg0: Regex.Companion?, _ arg1: Int32) -> Int32
}
