// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

@JavaInterface("kotlin.internal.RequireKotlin", extends: Annotation.self)
public struct RequireKotlin {
  @JavaMethod
  public func version() -> String

  @JavaMethod
  public func message() -> String

  @JavaMethod
  public func level() -> DeprecationLevel!

  @JavaMethod
  public func versionKind() -> RequireKotlinVersionKind!

  @JavaMethod
  public func errorCode() -> Int32

  @JavaMethod
  public func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  public func toString() -> String

  @JavaMethod
  public func hashCode() -> Int32

  @JavaMethod
  public func annotationType() -> JavaClass<Annotation>!
}
