// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.jvm.internal.RestrictedSuspendLambda", implements: SuspendFunction.self)
open class RestrictedSuspendLambda: RestrictedContinuationImpl {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Continuation<JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getArity() -> Int32

  @JavaMethod
  open override func toString() -> String
}
