// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.ResultKt")
open class ResultKt: JavaObject {

}
extension JavaClass<ResultKt> {
  @JavaStaticMethod
  public func createFailure(_ arg0: Throwable?) -> JavaObject!

  @JavaStaticMethod
  public func throwOnFailure(_ arg0: JavaObject?)
}
