// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.contracts.ReturnsNotNull", extends: SimpleEffect.self)
public struct ReturnsNotNull {
  @JavaMethod
  public func implies(_ arg0: Bool) -> ConditionalEffect!
}
