// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.comparisons.ReverseOrderComparator")
open class ReverseOrderComparator: JavaObject {
  @JavaMethod
  open func compare(_ arg0: JavaObject?, _ arg1: JavaObject?) -> Int32
}
extension JavaClass<ReverseOrderComparator> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: ReverseOrderComparator!
}
