// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.comparisons.ReversedComparator")
open class ReversedComparator<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  open func compare(_ arg0: JavaObject?, _ arg1: JavaObject?) -> Int32
}
