// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.coroutines.jvm.internal.RunSuspendKt")
open class RunSuspendKt: JavaObject {

}
extension JavaClass<RunSuspendKt> {
  @JavaStaticMethod
  public func runSuspend(_ arg0: Function1<JavaObject, JavaObject>?)
}
