// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.ScreenFloatValueRegEx")
open class ScreenFloatValueRegEx: JavaObject {

}
extension JavaClass<ScreenFloatValueRegEx> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: ScreenFloatValueRegEx!

  @JavaStaticField(isFinal: true)
  public var value: Regex!
}
