// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.uuid.SecureRandomHolder")
open class SecureRandomHolder: JavaObject {

}
extension JavaClass<SecureRandomHolder> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: SecureRandomHolder!
}
