// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaInterface("kotlin.sequences.Sequence")
public struct Sequence<T: AnyJavaObject> {
  @JavaMethod
  public func iterator() -> JavaIterator<JavaObject>!
}
