// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaLang
import JavaRuntime

@JavaClass("kotlin.sequences.SequenceScope")
open class SequenceScope<T: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func yield(_ arg0: JavaObject?, _ arg1: Continuation<JavaObject>?) -> JavaObject!

  @JavaMethod
  open func yieldAll(_ arg0: Iterable<JavaObject>?, _ arg1: Continuation<JavaObject>?) -> JavaObject!

  @JavaMethod
  open func yieldAll(_ arg0: Sequence<JavaObject>?, _ arg1: Continuation<JavaObject>?) -> JavaObject!

  @JavaMethod
  open func yieldAll(_ arg0: JavaIterator<JavaObject>?, _ arg1: Continuation<JavaObject>?) -> JavaObject!
}
