// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.sequences.SequencesKt__SequencesJVMKt")
open class SequencesKt__SequencesJVMKt: SequencesKt__SequenceBuilderKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
