// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.sequences.SequencesKt__SequenceBuilderKt")
open class SequencesKt__SequenceBuilderKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<SequencesKt__SequenceBuilderKt> {
  @JavaStaticMethod
  public func iterator(_ arg0: Function2<JavaObject, JavaObject, JavaObject>?) -> JavaIterator<JavaObject>!

  @JavaStaticMethod
  public func sequence(_ arg0: Function2<JavaObject, JavaObject, JavaObject>?) -> Sequence<JavaObject>!
}
