// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.SerializableKt")
open class SerializableKt: JavaObject {

}
extension JavaClass<SerializableKt> {
  @JavaStaticMethod
  public func Serializable$annotations()
}
