// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension SerializedMap {
  @JavaClass("kotlin.collections.builders.SerializedMap$Companion")
  open class Companion: JavaObject {

  }
}
