// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.ShortIterator", implements: JavaIterator<JavaShort>.self)
open class ShortIterator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  @JavaMethod
  open func nextShort() -> Int16

  @JavaMethod
  open func remove()

  @JavaMethod
  open func next() -> JavaShort!
}
