// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.contracts.SimpleEffect", extends: Effect.self)
public struct SimpleEffect {
  @JavaMethod
  public func implies(_ arg0: Bool) -> ConditionalEffect!
}
