// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.SlidingWindowKt")
open class SlidingWindowKt: JavaObject {

}
extension JavaClass<SlidingWindowKt> {
  @JavaStaticMethod
  public func checkWindowSizeStep(_ arg0: Int32, _ arg1: Int32)

  @JavaStaticMethod
  public func windowedSequence(_ arg0: Sequence<JavaObject>?, _ arg1: Int32, _ arg2: Int32, _ arg3: Bool, _ arg4: Bool) -> Sequence<List<JavaObject>>!

  @JavaStaticMethod
  public func windowedIterator(_ arg0: JavaIterator<JavaObject>?, _ arg1: Int32, _ arg2: Int32, _ arg3: Bool, _ arg4: Bool) -> JavaIterator<List<JavaObject>>!
}
