// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.encoding.StreamEncodingKt")
open class StreamEncodingKt: StreamEncodingKt__Base64IOStreamKt {

}
