// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

@JavaClass("kotlin.io.encoding.StreamEncodingKt__Base64IOStreamKt")
open class StreamEncodingKt__Base64IOStreamKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<StreamEncodingKt__Base64IOStreamKt> {
  @JavaStaticMethod
  public func decodingWith(_ arg0: InputStream?, _ arg1: Base64?) -> InputStream!

  @JavaStaticMethod
  public func encodingWith(_ arg0: OutputStream?, _ arg1: Base64?) -> OutputStream!
}
