// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime
import JavaUtil

@JavaClass("kotlin.text.StringsKt__StringsJVMKt")
open class StringsKt__StringsJVMKt: StringsKt__StringNumberConversionsKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<StringsKt__StringsJVMKt> {
  @JavaStaticMethod
  public func equals$default(_ arg0: String, _ arg1: String, _ arg2: Bool, _ arg3: Int32, _ arg4: JavaObject?) -> Bool

  @JavaStaticMethod
  public func replace$default(_ arg0: String, _ arg1: String, _ arg2: String, _ arg3: Bool, _ arg4: Int32, _ arg5: JavaObject?) -> String

  @JavaStaticMethod
  public func replace$default(_ arg0: String, _ arg1: UInt16, _ arg2: UInt16, _ arg3: Bool, _ arg4: Int32, _ arg5: JavaObject?) -> String

  @JavaStaticMethod
  public func replaceFirst$default(_ arg0: String, _ arg1: String, _ arg2: String, _ arg3: Bool, _ arg4: Int32, _ arg5: JavaObject?) -> String

  @JavaStaticMethod
  public func replaceFirst$default(_ arg0: String, _ arg1: UInt16, _ arg2: UInt16, _ arg3: Bool, _ arg4: Int32, _ arg5: JavaObject?) -> String

  @JavaStaticMethod
  public func concatToString(_ arg0: [UInt16]) -> String

  @JavaStaticMethod
  public func concatToString(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32) -> String

  @JavaStaticMethod
  public func concatToString$default(_ arg0: [UInt16], _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: JavaObject?) -> String

  @JavaStaticMethod
  public func toCharArray$default(_ arg0: String, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: JavaObject?) -> [UInt16]

  @JavaStaticMethod
  public func decodeToString(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32, _ arg3: Bool) -> String

  @JavaStaticMethod
  public func decodeToString(_ arg0: [Int8]) -> String

  @JavaStaticMethod
  public func decodeToString$default(_ arg0: [Int8], _ arg1: Int32, _ arg2: Int32, _ arg3: Bool, _ arg4: Int32, _ arg5: JavaObject?) -> String

  @JavaStaticMethod
  public func encodeToByteArray(_ arg0: String, _ arg1: Int32, _ arg2: Int32, _ arg3: Bool) -> [Int8]

  @JavaStaticMethod
  public func encodeToByteArray(_ arg0: String) -> [Int8]

  @JavaStaticMethod
  public func encodeToByteArray$default(_ arg0: String, _ arg1: Int32, _ arg2: Int32, _ arg3: Bool, _ arg4: Int32, _ arg5: JavaObject?) -> [Int8]

  @JavaStaticMethod
  public func startsWith$default(_ arg0: String, _ arg1: String, _ arg2: Bool, _ arg3: Int32, _ arg4: JavaObject?) -> Bool

  @JavaStaticMethod
  public func startsWith$default(_ arg0: String, _ arg1: String, _ arg2: Int32, _ arg3: Bool, _ arg4: Int32, _ arg5: JavaObject?) -> Bool

  @JavaStaticMethod
  public func endsWith$default(_ arg0: String, _ arg1: String, _ arg2: Bool, _ arg3: Int32, _ arg4: JavaObject?) -> Bool

  @JavaStaticMethod
  public func compareTo$default(_ arg0: String, _ arg1: String, _ arg2: Bool, _ arg3: Int32, _ arg4: JavaObject?) -> Int32

  @JavaStaticMethod
  public func regionMatches$default(_ arg0: CharSequence?, _ arg1: Int32, _ arg2: CharSequence?, _ arg3: Int32, _ arg4: Int32, _ arg5: Bool, _ arg6: Int32, _ arg7: JavaObject?) -> Bool

  @JavaStaticMethod
  public func regionMatches$default(_ arg0: String, _ arg1: Int32, _ arg2: String, _ arg3: Int32, _ arg4: Int32, _ arg5: Bool, _ arg6: Int32, _ arg7: JavaObject?) -> Bool

  @JavaStaticMethod
  public func decapitalize(_ arg0: String) -> String

  @JavaStaticMethod
  public func decapitalize(_ arg0: String, _ arg1: Locale?) -> String

  @JavaStaticMethod
  public func equals(_ arg0: String, _ arg1: String, _ arg2: Bool) -> Bool

  @JavaStaticMethod
  public func compareTo(_ arg0: String, _ arg1: String, _ arg2: Bool) -> Int32

  @JavaStaticMethod
  public func contentEquals(_ arg0: CharSequence?, _ arg1: CharSequence?) -> Bool

  @JavaStaticMethod
  public func contentEquals(_ arg0: CharSequence?, _ arg1: CharSequence?, _ arg2: Bool) -> Bool

  @JavaStaticMethod
  public func regionMatches(_ arg0: String, _ arg1: Int32, _ arg2: String, _ arg3: Int32, _ arg4: Int32, _ arg5: Bool) -> Bool

  @JavaStaticMethod
  public func regionMatches(_ arg0: CharSequence?, _ arg1: Int32, _ arg2: CharSequence?, _ arg3: Int32, _ arg4: Int32, _ arg5: Bool) -> Bool

  @JavaStaticMethod
  public func startsWith(_ arg0: String, _ arg1: String, _ arg2: Int32, _ arg3: Bool) -> Bool

  @JavaStaticMethod
  public func startsWith(_ arg0: String, _ arg1: String, _ arg2: Bool) -> Bool

  @JavaStaticMethod
  public func replace(_ arg0: String, _ arg1: String, _ arg2: String, _ arg3: Bool) -> String

  @JavaStaticMethod
  public func replace(_ arg0: String, _ arg1: UInt16, _ arg2: UInt16, _ arg3: Bool) -> String

  @JavaStaticMethod
  public func replaceFirst(_ arg0: String, _ arg1: String, _ arg2: String, _ arg3: Bool) -> String

  @JavaStaticMethod
  public func replaceFirst(_ arg0: String, _ arg1: UInt16, _ arg2: UInt16, _ arg3: Bool) -> String

  @JavaStaticMethod
  public func `repeat`(_ arg0: CharSequence?, _ arg1: Int32) -> String

  @JavaStaticMethod
  public func toCharArray(_ arg0: String, _ arg1: Int32, _ arg2: Int32) -> [UInt16]

  @JavaStaticMethod
  public func endsWith(_ arg0: String, _ arg1: String, _ arg2: Bool) -> Bool

  @JavaStaticMethod
  public func capitalize(_ arg0: String, _ arg1: Locale?) -> String

  @JavaStaticMethod
  public func capitalize(_ arg0: String) -> String
}
