// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.StringsKt__RegexExtensionsKt")
open class StringsKt__RegexExtensionsKt: StringsKt__RegexExtensionsJVMKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
