// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.text.StringsKt___StringsJvmKt")
open class StringsKt___StringsJvmKt: StringsKt__StringsKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<StringsKt___StringsJvmKt> {
  @JavaStaticMethod
  public func min(_ arg0: CharSequence?) -> JavaCharacter!

  @JavaStaticMethod
  public func max(_ arg0: CharSequence?) -> JavaCharacter!

  @JavaStaticMethod
  public func maxBy(_ arg0: CharSequence?, _ arg1: Function1<JavaObject, Comparable>?) -> JavaCharacter!

  @JavaStaticMethod
  public func minBy(_ arg0: CharSequence?, _ arg1: Function1<JavaObject, Comparable>?) -> JavaCharacter!
}
