// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.StringsKt__AppendableKt")
open class StringsKt__AppendableKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<StringsKt__AppendableKt> {
  @JavaStaticMethod
  public func appendRange(_ arg0: Appendable?, _ arg1: CharSequence?, _ arg2: Int32, _ arg3: Int32) -> Appendable!

  @JavaStaticMethod
  public func appendElement(_ arg0: Appendable?, _ arg1: JavaObject?, _ arg2: Function1<JavaObject, CharSequence>?)

  @JavaStaticMethod
  public func append(_ arg0: Appendable?, _ arg1: [CharSequence?]) -> Appendable!
}
