// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.StringsKt__StringNumberConversionsJVMKt")
open class StringsKt__StringNumberConversionsJVMKt: StringsKt__StringBuilderKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<StringsKt__StringNumberConversionsJVMKt> {
  @JavaStaticMethod
  public func toFloatOrNull(_ arg0: String) -> JavaFloat!

  @JavaStaticMethod
  public func toDoubleOrNull(_ arg0: String) -> JavaDouble!
}
