// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaLang
import JavaRuntime

@JavaClass("kotlin.text.StringsKt__StringBuilderJVMKt")
open class StringsKt__StringBuilderJVMKt: StringsKt__RegexExtensionsKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<StringsKt__StringBuilderJVMKt> {
  @JavaStaticMethod
  public func clear(_ arg0: StringBuilder?) -> StringBuilder!

  @JavaStaticMethod
  public func appendln(_ arg0: StringBuilder?) -> StringBuilder!

  @JavaStaticMethod
  public func appendln(_ arg0: Appendable?) -> Appendable!
}
