// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.StringsKt__RegexExtensionsJVMKt")
open class StringsKt__RegexExtensionsJVMKt: StringsKt__IndentKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
