// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.SystemProperties")
open class SystemProperties: JavaObject {

}
extension JavaClass<SystemProperties> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: SystemProperties!

  @JavaStaticField(isFinal: true)
  public var LINE_SEPARATOR: String
}
