// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.time.TestTimeSource")
open class TestTimeSource: AbstractLongTimeSource {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

  // @JavaMethod
//  open func`plusAssign-LRDsOJo`(_ arg0: Int64)

@JavaMethod
  open override func read() -> Int64
}
extension JavaClass<TestTimeSource> {
  @JavaStaticField(isFinal: true)
  public var Companion: TimeSource.Companion!
}
