// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaKitCollection
import JavaKitNetwork
import JavaRuntime

@JavaClass("kotlin.io.TextStreamsKt")
open class TextStreamsKt: JavaObject {

}
extension JavaClass<TextStreamsKt> {
  @JavaStaticMethod
  public func copyTo$default(_ arg0: Reader?, _ arg1: Writer?, _ arg2: Int32, _ arg3: Int32, _ arg4: JavaObject?) -> Int64

  @JavaStaticMethod
  public func readText(_ arg0: Reader?) -> String

  @JavaStaticMethod
  public func forEachLine(_ arg0: Reader?, _ arg1: Function1<JavaObject, Unit>?)

  @JavaStaticMethod
  public func lineSequence(_ arg0: BufferedReader?) -> Sequence<JavaString>!

  @JavaStaticMethod
  public func readLines(_ arg0: Reader?) -> List<JavaString>!

  @JavaStaticMethod
  public func useLines(_ arg0: Reader?, _ arg1: Function1<JavaObject, JavaObject>?) -> JavaObject!

  @JavaStaticMethod
  public func readBytes(_ arg0: URL?) -> [Int8]

  @JavaStaticMethod
  public func copyTo(_ arg0: Reader?, _ arg1: Writer?, _ arg2: Int32) -> Int64
}
