// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.text.TypeAliasesKt")
open class TextTypeAliasesKt: JavaObject {

}
extension JavaClass<TextTypeAliasesKt> {
  @JavaStaticMethod
  public func Appendable$annotations()

  @JavaStaticMethod
  public func StringBuilder$annotations()

  @JavaStaticMethod
  public func CharacterCodingException$annotations()
}
