// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.ThrowsKt")
open class ThrowsKt: JavaObject {

}
extension JavaClass<ThrowsKt> {
  @JavaStaticMethod
  public func Throws$annotations()
}
