// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension TimeSource.Monotonic {
  @JavaClass("kotlin.time.TimeSource$Monotonic$ValueTimeMark", implements: ComparableTimeMark.self)
  open class ValueTimeMark: JavaObject {
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func compareTo(_ arg0: ComparableTimeMark?) -> Int32

  @JavaMethod
  open func compareTo(_ arg0: JavaObject?) -> Int32
  
  @JavaMethod
  open func hasPassedNow() -> Bool

  @JavaMethod
  open func hasNotPassedNow() -> Bool
  }
}