// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension TimeMark {
  @JavaClass("kotlin.time.TimeMark$DefaultImpls")
  open class DefaultImpls: JavaObject {

  }
}
extension JavaClass<TimeMark.DefaultImpls> {
  @JavaStaticMethod
  public func`plus-LRDsOJo`(_ arg0: TimeMark?, _ arg1: Int64) -> TimeMark!

@JavaStaticMethod
  public func`minus-LRDsOJo`(_ arg0: TimeMark?, _ arg1: Int64) -> TimeMark!

@JavaStaticMethod
  public func hasPassedNow(_ arg0: TimeMark?) -> Bool

  @JavaStaticMethod
  public func hasNotPassedNow(_ arg0: TimeMark?) -> Bool
}
