// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaInterface("kotlin.time.TimeMark")
public struct TimeMark {

  @JavaMethod
  public func hasPassedNow() -> Bool

  @JavaMethod
  public func hasNotPassedNow() -> Bool
}
