// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension TimeSource {
  @JavaClass("kotlin.time.TimeSource$Monotonic", implements: TimeSource.WithComparableMarks.self)
  open class Monotonic: JavaObject {
  @JavaMethod
  open func markNow() -> TimeMark!

  @JavaMethod
  open func markNow() -> ComparableTimeMark!

  // @JavaMethod
//  open func`markNow-z9LOYto`() -> Int64

  @JavaMethod
  open override func toString() -> String
  }
}
extension JavaClass<TimeSource.Monotonic> {
  @JavaStaticField(isFinal: true)
  public var INSTANCE: TimeSource.Monotonic!

  @JavaStaticField(isFinal: true)
  public var Companion: TimeSource.Companion!
}
