// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime
import JavaUtil

@JavaClass("kotlin.concurrent.TimersKt")
open class TimersKt: JavaObject {

}
extension JavaClass<TimersKt> {
  @JavaStaticMethod
  public func timer(_ arg0: String, _ arg1: Bool) -> Timer!
}
