// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.system.TimingKt")
open class TimingKt: JavaObject {

}
extension JavaClass<TimingKt> {
  @JavaStaticMethod
  public func measureTimeMillis(_ arg0: Function0<Unit>?) -> Int64

  @JavaStaticMethod
  public func measureNanoTime(_ arg0: Function0<Unit>?) -> Int64
}
