// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.sequences.TransformingSequence", implements: Sequence<JavaObject>.self)
open class TransformingSequence<T: AnyJavaObject, R: AnyJavaObject>: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Sequence<JavaObject>?, _ arg1: Function1<JavaObject, JavaObject>?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func flatten$kotlin_stdlib(_ arg0: Function1<JavaObject, JavaIterator<JavaObject>>?) -> Sequence<JavaObject>!

  @JavaMethod
  open func iterator() -> JavaIterator<JavaObject>!
}
extension JavaClass {
  @JavaStaticMethod
  public func access$getSequence$p<T: AnyJavaObject, R: AnyJavaObject>(_ arg0: TransformingSequence?) -> Sequence! where ObjectType == TransformingSequence<T, R>

  @JavaStaticMethod
  public func access$getTransformer$p<T: AnyJavaObject, R: AnyJavaObject>(_ arg0: TransformingSequence?) -> Function1! where ObjectType == TransformingSequence<T, R>
}
