// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

@JavaClass("kotlin.reflect.TypesJVMKt")
open class TypesJVMKt: JavaObject {

}
extension JavaClass<TypesJVMKt> {
  @JavaStaticMethod
  public func getJavaType(_ arg0: KType?) -> Type!

  @JavaStaticMethod
  public func access$typeToString(_ arg0: Type?) -> String

  @JavaStaticMethod
  public func getJavaType$annotations(_ arg0: KType?)

  @JavaStaticMethod
  public func access$computeJavaType(_ arg0: KType?, _ arg1: Bool) -> Type!
}
