// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

@JavaClass("kotlin.reflect.TypeVariableImpl", implements: TypeVariable<GenericDeclaration>.self, TypeImpl.self)
open class TypeVariableImpl: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: KTypeParameter?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getGenericDeclaration() -> GenericDeclaration!

  @JavaMethod
  open func getName() -> String

  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func getBounds() -> [Type?]

  @JavaMethod
  open func getTypeName() -> String

  @JavaMethod
  open func getAnnotation(_ arg0: JavaClass<Annotation>?) -> Annotation!

  @JavaMethod
  open func getAnnotations() -> [Annotation?]

  @JavaMethod
  open func getDeclaredAnnotations() -> [Annotation?]
}
