// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.reflect.TypeOfKt")
open class TypeOfKt: JavaObject {

}
extension JavaClass<TypeOfKt> {
  @JavaStaticMethod
  public func typeOf() -> KType!
}
