// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension TypeReference {
  @JavaClass("kotlin.jvm.internal.TypeReference$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}
extension JavaClass<TypeReference.WhenMappings> {
  @JavaStaticField(isFinal: true)
  public var $EnumSwitchMapping$0: [Int32]
}
