// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension TypesJVMKt {
  @JavaClass("kotlin.reflect.TypesJVMKt$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}
extension JavaClass<TypesJVMKt.WhenMappings> {
  @JavaStaticField(isFinal: true)
  public var $EnumSwitchMapping$0: [Int32]
}
