// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension TypesJVMKt {
  @JavaClass("kotlin.reflect.TypesJVMKt$WhenMappings")
  open class WhenMappings: JavaObject {

  }
}