// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitReflection
import JavaRuntime

@JavaInterface("kotlin.reflect.TypeImpl", extends: Type.self)
public struct TypeImpl {
  @JavaMethod
  public func getTypeName() -> String
}
