// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaLang
import JavaRuntime
import JavaUtil

@JavaClass("kotlin.jvm.internal.TypeIntrinsics")
open class TypeIntrinsics: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<TypeIntrinsics> {
  @JavaStaticMethod
  public func isMutableListIterator(_ arg0: JavaObject?) -> Bool

  @JavaStaticMethod
  public func asMutableListIterator(_ arg0: JavaObject?, _ arg1: String) -> ListIterator!

  @JavaStaticMethod
  public func asMutableListIterator(_ arg0: JavaObject?) -> ListIterator!

  @JavaStaticMethod
  public func isMutableCollection(_ arg0: JavaObject?) -> Bool

  @JavaStaticMethod
  public func beforeCheckcastToFunctionOfArity(_ arg0: JavaObject?, _ arg1: Int32) -> JavaObject!

  @JavaStaticMethod
  public func beforeCheckcastToFunctionOfArity(_ arg0: JavaObject?, _ arg1: Int32, _ arg2: String) -> JavaObject!

  @JavaStaticMethod
  public func asMutableCollection(_ arg0: JavaObject?) -> JavaCollection!

  @JavaStaticMethod
  public func asMutableCollection(_ arg0: JavaObject?, _ arg1: String) -> JavaCollection!

  @JavaStaticMethod
  public func asMutableMapEntry(_ arg0: JavaObject?, _ arg1: String) -> Map.Entry!

  @JavaStaticMethod
  public func asMutableMapEntry(_ arg0: JavaObject?) -> Map.Entry!

  @JavaStaticMethod
  public func asMutableMap(_ arg0: JavaObject?) -> Map!

  @JavaStaticMethod
  public func asMutableMap(_ arg0: JavaObject?, _ arg1: String) -> Map!

  @JavaStaticMethod
  public func throwCce(_ arg0: String)

  @JavaStaticMethod
  public func throwCce(_ arg0: JavaObject?, _ arg1: String)

  @JavaStaticMethod
  public func throwCce(_ arg0: ClassCastException?) -> ClassCastException!

  @JavaStaticMethod
  public func isMutableIterator(_ arg0: JavaObject?) -> Bool

  @JavaStaticMethod
  public func asMutableIterator(_ arg0: JavaObject?) -> JavaIterator!

  @JavaStaticMethod
  public func asMutableIterator(_ arg0: JavaObject?, _ arg1: String) -> JavaIterator!

  @JavaStaticMethod
  public func castToIterator(_ arg0: JavaObject?) -> JavaIterator!

  @JavaStaticMethod
  public func castToListIterator(_ arg0: JavaObject?) -> ListIterator!

  @JavaStaticMethod
  public func isMutableIterable(_ arg0: JavaObject?) -> Bool

  @JavaStaticMethod
  public func castToIterable(_ arg0: JavaObject?) -> Iterable!

  @JavaStaticMethod
  public func castToCollection(_ arg0: JavaObject?) -> JavaCollection!

  @JavaStaticMethod
  public func isMutableList(_ arg0: JavaObject?) -> Bool

  @JavaStaticMethod
  public func asMutableList(_ arg0: JavaObject?, _ arg1: String) -> List!

  @JavaStaticMethod
  public func asMutableList(_ arg0: JavaObject?) -> List!

  @JavaStaticMethod
  public func castToList(_ arg0: JavaObject?) -> List!

  @JavaStaticMethod
  public func isMutableSet(_ arg0: JavaObject?) -> Bool

  @JavaStaticMethod
  public func asMutableSet(_ arg0: JavaObject?) -> JavaSet!

  @JavaStaticMethod
  public func asMutableSet(_ arg0: JavaObject?, _ arg1: String) -> JavaSet!

  @JavaStaticMethod
  public func castToSet(_ arg0: JavaObject?) -> JavaSet!

  @JavaStaticMethod
  public func isMutableMap(_ arg0: JavaObject?) -> Bool

  @JavaStaticMethod
  public func castToMap(_ arg0: JavaObject?) -> Map!

  @JavaStaticMethod
  public func isMutableMapEntry(_ arg0: JavaObject?) -> Bool

  @JavaStaticMethod
  public func castToMapEntry(_ arg0: JavaObject?) -> Map.Entry!

  @JavaStaticMethod
  public func getFunctionArity(_ arg0: JavaObject?) -> Int32

  @JavaStaticMethod
  public func isFunctionOfArity(_ arg0: JavaObject?, _ arg1: Int32) -> Bool

  @JavaStaticMethod
  public func asMutableIterable(_ arg0: JavaObject?) -> Iterable!

  @JavaStaticMethod
  public func asMutableIterable(_ arg0: JavaObject?, _ arg1: String) -> Iterable!
}
