// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.unsigned.UArraysKt___UArraysJvmKt")
open class UArraysKt___UArraysJvmKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<UArraysKt___UArraysJvmKt> {
  @JavaStaticMethod
  public func`asList--ajY-9A`(_ arg0: [Int32]) -> List<UInt>!

@JavaStaticMethod
  public func`asList-QwZRm1k`(_ arg0: [Int64]) -> List<ULong>!

@JavaStaticMethod
  public func`asList-GBYM_sE`(_ arg0: [Int8]) -> List<UByte>!

@JavaStaticMethod
  public func`asList-rL5Bavg`(_ arg0: [Int16]) -> List<UShort>!

@JavaStaticMethod
  public func`binarySearch-2fe2U9s`(_ arg0: [Int32], _ arg1: Int32, _ arg2: Int32, _ arg3: Int32) -> Int32

@JavaStaticMethod
  public func`binarySearch-2fe2U9s$default`(_ arg0: [Int32], _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: JavaObject?) -> Int32

@JavaStaticMethod
  public func`binarySearch-K6DWlUc`(_ arg0: [Int64], _ arg1: Int64, _ arg2: Int32, _ arg3: Int32) -> Int32

@JavaStaticMethod
  public func`binarySearch-K6DWlUc$default`(_ arg0: [Int64], _ arg1: Int64, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: JavaObject?) -> Int32

@JavaStaticMethod
  public func`binarySearch-WpHrYlw`(_ arg0: [Int8], _ arg1: Int8, _ arg2: Int32, _ arg3: Int32) -> Int32

@JavaStaticMethod
  public func`binarySearch-WpHrYlw$default`(_ arg0: [Int8], _ arg1: Int8, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: JavaObject?) -> Int32

@JavaStaticMethod
  public func`binarySearch-EtDCXyQ`(_ arg0: [Int16], _ arg1: Int16, _ arg2: Int32, _ arg3: Int32) -> Int32

@JavaStaticMethod
  public func`binarySearch-EtDCXyQ$default`(_ arg0: [Int16], _ arg1: Int16, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: JavaObject?) -> Int32

@JavaStaticMethod
  public func`max--ajY-9A`(_ arg0: [Int32]) -> UInt!

@JavaStaticMethod
  public func`max-QwZRm1k`(_ arg0: [Int64]) -> ULong!

@JavaStaticMethod
  public func`max-GBYM_sE`(_ arg0: [Int8]) -> UByte!

@JavaStaticMethod
  public func`max-rL5Bavg`(_ arg0: [Int16]) -> UShort!

@JavaStaticMethod
  public func`min--ajY-9A`(_ arg0: [Int32]) -> UInt!

@JavaStaticMethod
  public func`min-QwZRm1k`(_ arg0: [Int64]) -> ULong!

@JavaStaticMethod
  public func`min-GBYM_sE`(_ arg0: [Int8]) -> UByte!

@JavaStaticMethod
  public func `min-rL5Bavg`(_ arg0: [Int16]) -> UShort!
}
