// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.collections.unsigned.UArraysKt___UArraysKt")
open class UArraysKt___UArraysKt: UArraysKt___UArraysJvmKt {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
@JavaStaticMethod
  public func toUByteArray(_ arg0: [UByte?]) -> [Int8]

  @JavaStaticMethod
  public func toUIntArray(_ arg0: [UInt?]) -> [Int32]

  @JavaStaticMethod
  public func toULongArray(_ arg0: [ULong?]) -> [Int64]

  @JavaStaticMethod
  public func toUShortArray(_ arg0: [UShort?]) -> [Int16]

  @JavaStaticMethod
  public func sumOfUByte(_ arg0: [UByte?]) -> Int32

  @JavaStaticMethod
  public func sumOfUShort(_ arg0: [UShort?]) -> Int32

  @JavaStaticMethod
  public func sumOfUInt(_ arg0: [UInt?]) -> Int32

  @JavaStaticMethod
  public func sumOfULong(_ arg0: [ULong?]) -> Int64
}
