// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension UByteArray {
  @JavaClass("kotlin.UByteArray$Iterator", implements: JavaIterator<UByte>.self)
  open class Iterator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [Int8], environment: JNIEnvironment? = nil)

  // @JavaMethod
//  open func`next-w2LRezQ`() -> Int8

  @JavaMethod
  open func remove()

  @JavaMethod
  open func hasNext() -> Bool

  @JavaMethod
  open func next() -> JavaObject!
  }
}
