// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaLang
import JavaRuntime

@JavaClass("kotlin.collections.UCollectionsKt___UCollectionsKt")
open class UCollectionsKt___UCollectionsKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<UCollectionsKt___UCollectionsKt> {
  @JavaStaticMethod
  public func sumOfUInt(_ arg0: Iterable<UInt>?) -> Int32

  @JavaStaticMethod
  public func sumOfULong(_ arg0: Iterable<ULong>?) -> Int64

  @JavaStaticMethod
  public func sumOfUByte(_ arg0: Iterable<UByte>?) -> Int32

  @JavaStaticMethod
  public func sumOfUShort(_ arg0: Iterable<UShort>?) -> Int32

  @JavaStaticMethod
  public func toUByteArray(_ arg0: JavaCollection<UByte>?) -> [Int8]

  @JavaStaticMethod
  public func toUIntArray(_ arg0: JavaCollection<UInt>?) -> [Int32]

  @JavaStaticMethod
  public func toULongArray(_ arg0: JavaCollection<ULong>?) -> [Int64]

  @JavaStaticMethod
  public func toUShortArray(_ arg0: JavaCollection<UShort>?) -> [Int16]
}
