// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.ranges.UIntProgression")
open class UIntProgression: JavaObject {
  @JavaMethod
  open func getStep() -> Int32

  // @JavaMethod
//  open func`getFirst-pVg5ArA`() -> Int32

// @JavaMethod
//  open func`getLast-pVg5ArA`() -> Int32

@JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

  @JavaMethod
  open override func toString() -> String

  @JavaMethod
  open override func hashCode() -> Int32

  @JavaMethod
  open func isEmpty() -> Bool

  @JavaMethod
  open func iterator() -> JavaIterator<UInt>!
}
extension JavaClass<UIntProgression> {
  @JavaStaticField(isFinal: true)
  public var Companion: UIntProgression.Companion!
}
