// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

@JavaClass("kotlin.ranges.ULongProgressionIterator", implements: JavaIterator<ULong>.self, KMappedMarker.self)
open class ULongProgressionIterator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int64, _ arg1: Int64, _ arg2: Int64, _ arg3: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func remove()

  @JavaMethod
  open func hasNext() -> Bool

  @JavaMethod
  open func next() -> JavaObject!

//  @JavaMethod
//  open func `next-s-VKNKU`() -> Int64
}
