// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaKitCollection
import JavaRuntime

extension ULongArray {
  @JavaClass("kotlin.ULongArray$Iterator", implements: JavaIterator<ULong>.self)
  open class Iterator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: [Int64], environment: JNIEnvironment? = nil)

  @JavaMethod
  open func`next-s-VKNKU`() -> Int64

  @JavaMethod
  open func remove()

  @JavaMethod
  open func hasNext() -> Bool

  @JavaMethod
  open func next() -> JavaObject!
  }
}
