// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension ULongRange {
  @JavaClass("kotlin.ranges.ULongRange$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)

  @JavaMethod
  open func getEMPTY() -> ULongRange!
  }
}
