// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.UnsignedKt")
open class UnsignedKt: JavaObject {

}
extension JavaClass<UnsignedKt> {
  
  @JavaStaticMethod
  public func ulongToString(_ arg0: Int64, _ arg1: Int32) -> String

  @JavaStaticMethod
  public func uintCompare(_ arg0: Int32, _ arg1: Int32) -> Int32

  @JavaStaticMethod
  public func uintToDouble(_ arg0: Int32) -> Double

  @JavaStaticMethod
  public func doubleToUInt(_ arg0: Double) -> Int32

  @JavaStaticMethod
  public func ulongCompare(_ arg0: Int64, _ arg1: Int64) -> Int32

  @JavaStaticMethod
  public func ulongToDouble(_ arg0: Int64) -> Double

  @JavaStaticMethod
  public func doubleToULong(_ arg0: Double) -> Int64
}
