// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.sequences.USequencesKt___USequencesKt")
open class USequencesKt___USequencesKt: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<USequencesKt___USequencesKt> {
  @JavaStaticMethod
  public func sumOfUInt(_ arg0: Sequence<UInt>?) -> Int32

  @JavaStaticMethod
  public func sumOfULong(_ arg0: Sequence<ULong>?) -> Int64

  @JavaStaticMethod
  public func sumOfUByte(_ arg0: Sequence<UByte>?) -> Int32

  @JavaStaticMethod
  public func sumOfUShort(_ arg0: Sequence<UShort>?) -> Int32
}
