// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

@JavaClass("kotlin.concurrent.VolatileKt")
open class VolatileKt: JavaObject {

}
extension JavaClass<VolatileKt> {
  @JavaStaticMethod
  public func Volatile$annotations()
}
