// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension WildcardTypeImpl {
  @JavaClass("kotlin.reflect.WildcardTypeImpl$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  open func getSTAR() -> WildcardTypeImpl!
  }
}
