// Auto-generated by Java-to-Swift wrapper generator.
import JavaIO
import JavaKit
import JavaRuntime

@JavaClass("kotlin.random.XorWowRandom", implements: Serializable.self)
open class XorWowRandom: Random {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32, _ arg5: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  @_nonoverride public convenience init(_ arg0: Int32, _ arg1: Int32, environment: JNIEnvironment? = nil)

  @JavaMethod
  open override func nextInt() -> Int32

  @JavaMethod
  open override func nextBits(_ arg0: Int32) -> Int32
}
extension JavaClass<XorWowRandom> {
  @JavaStaticField(isFinal: true)
  public var Default: Random.Default!
}
