// Auto-generated by Java-to-Swift wrapper generator.
import JavaKit
import JavaRuntime

extension XorWowRandom {
  @JavaClass("kotlin.random.XorWowRandom$Companion")
  open class Companion: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: DefaultConstructorMarker?, environment: JNIEnvironment? = nil)
  }
}
